/* AutomaticScrollBox.c generated by valac 0.32.1, the Vala compiler
 * generated from AutomaticScrollBox.vala, do not modify */

/*
 * This file is part of haste-applet
 *
 * Copyright (C) 2016 Stefan Ric <stfric369@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX (haste_applet_automatic_scroll_box_get_type ())
#define HASTE_APPLET_AUTOMATIC_SCROLL_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBox))
#define HASTE_APPLET_AUTOMATIC_SCROLL_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBoxClass))
#define HASTE_APPLET_IS_AUTOMATIC_SCROLL_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX))
#define HASTE_APPLET_IS_AUTOMATIC_SCROLL_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX))
#define HASTE_APPLET_AUTOMATIC_SCROLL_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBoxClass))

typedef struct _HasteAppletAutomaticScrollBox HasteAppletAutomaticScrollBox;
typedef struct _HasteAppletAutomaticScrollBoxClass HasteAppletAutomaticScrollBoxClass;
typedef struct _HasteAppletAutomaticScrollBoxPrivate HasteAppletAutomaticScrollBoxPrivate;

struct _HasteAppletAutomaticScrollBox {
	GtkScrolledWindow parent_instance;
	HasteAppletAutomaticScrollBoxPrivate * priv;
};

struct _HasteAppletAutomaticScrollBoxClass {
	GtkScrolledWindowClass parent_class;
};

struct _HasteAppletAutomaticScrollBoxPrivate {
	gint _max_height;
};


static gpointer haste_applet_automatic_scroll_box_parent_class = NULL;
static GType haste_applet_automatic_scroll_box_type_id = 0;

GType haste_applet_automatic_scroll_box_get_type (void) G_GNUC_CONST;
GType haste_applet_automatic_scroll_box_register_type (GTypeModule * module);
#define HASTE_APPLET_AUTOMATIC_SCROLL_BOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBoxPrivate))
enum  {
	HASTE_APPLET_AUTOMATIC_SCROLL_BOX_DUMMY_PROPERTY,
	HASTE_APPLET_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT
};
HasteAppletAutomaticScrollBox* haste_applet_automatic_scroll_box_new (GtkAdjustment* hadj, GtkAdjustment* vadj);
HasteAppletAutomaticScrollBox* haste_applet_automatic_scroll_box_construct (GType object_type, GtkAdjustment* hadj, GtkAdjustment* vadj);
static void haste_applet_automatic_scroll_box_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height);
gint haste_applet_automatic_scroll_box_get_max_height (HasteAppletAutomaticScrollBox* self);
static void haste_applet_automatic_scroll_box_real_get_preferred_height (GtkWidget* base, gint* minimum_height, gint* natural_height);
void haste_applet_automatic_scroll_box_set_max_height (HasteAppletAutomaticScrollBox* self, gint value);
static GObject * haste_applet_automatic_scroll_box_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _gtk_widget_queue_resize_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void haste_applet_automatic_scroll_box_finalize (GObject* obj);
static void _vala_haste_applet_automatic_scroll_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_haste_applet_automatic_scroll_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


HasteAppletAutomaticScrollBox* haste_applet_automatic_scroll_box_construct (GType object_type, GtkAdjustment* hadj, GtkAdjustment* vadj) {
	HasteAppletAutomaticScrollBox * self = NULL;
	GtkAdjustment* _tmp0_ = NULL;
	GtkAdjustment* _tmp1_ = NULL;
	_tmp0_ = hadj;
	_tmp1_ = vadj;
	self = (HasteAppletAutomaticScrollBox*) g_object_new (object_type, "hadjustment", _tmp0_, "vadjustment", _tmp1_, NULL);
	return self;
}


HasteAppletAutomaticScrollBox* haste_applet_automatic_scroll_box_new (GtkAdjustment* hadj, GtkAdjustment* vadj) {
	return haste_applet_automatic_scroll_box_construct (HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, hadj, vadj);
}


static void haste_applet_automatic_scroll_box_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height) {
	HasteAppletAutomaticScrollBox * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	GtkWidget* child = NULL;
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	self = (HasteAppletAutomaticScrollBox*) base;
	_tmp0_ = gtk_bin_get_child ((GtkBin*) self);
	child = _tmp0_;
	_tmp1_ = child;
	if (_tmp1_ != NULL) {
		GtkWidget* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		_tmp2_ = child;
		_tmp3_ = width;
		gtk_widget_get_preferred_height_for_width (_tmp2_, _tmp3_, &_tmp4_, &_tmp5_);
		_vala_minimum_height = _tmp4_;
		_vala_natural_height = _tmp5_;
		_tmp6_ = self->priv->_max_height;
		_tmp7_ = _vala_minimum_height;
		_tmp8_ = MIN (_tmp6_, _tmp7_);
		_vala_minimum_height = _tmp8_;
		_tmp9_ = self->priv->_max_height;
		_tmp10_ = _vala_natural_height;
		_tmp11_ = MIN (_tmp9_, _tmp10_);
		_vala_natural_height = _tmp11_;
	} else {
		gint _tmp12_ = 0;
		_vala_natural_height = 0;
		_tmp12_ = _vala_natural_height;
		_vala_minimum_height = _tmp12_;
	}
	if (minimum_height) {
		*minimum_height = _vala_minimum_height;
	}
	if (natural_height) {
		*natural_height = _vala_natural_height;
	}
}


static void haste_applet_automatic_scroll_box_real_get_preferred_height (GtkWidget* base, gint* minimum_height, gint* natural_height) {
	HasteAppletAutomaticScrollBox * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	GtkWidget* child = NULL;
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	self = (HasteAppletAutomaticScrollBox*) base;
	_tmp0_ = gtk_bin_get_child ((GtkBin*) self);
	child = _tmp0_;
	_tmp1_ = child;
	if (_tmp1_ != NULL) {
		GtkWidget* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		_tmp2_ = child;
		gtk_widget_get_preferred_height (_tmp2_, &_tmp3_, &_tmp4_);
		_vala_minimum_height = _tmp3_;
		_vala_natural_height = _tmp4_;
		_tmp5_ = self->priv->_max_height;
		_tmp6_ = _vala_minimum_height;
		_tmp7_ = MIN (_tmp5_, _tmp6_);
		_vala_minimum_height = _tmp7_;
		_tmp8_ = self->priv->_max_height;
		_tmp9_ = _vala_natural_height;
		_tmp10_ = MIN (_tmp8_, _tmp9_);
		_vala_natural_height = _tmp10_;
	} else {
		gint _tmp11_ = 0;
		_vala_natural_height = 0;
		_tmp11_ = _vala_natural_height;
		_vala_minimum_height = _tmp11_;
	}
	if (minimum_height) {
		*minimum_height = _vala_minimum_height;
	}
	if (natural_height) {
		*natural_height = _vala_natural_height;
	}
}


gint haste_applet_automatic_scroll_box_get_max_height (HasteAppletAutomaticScrollBox* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_max_height;
	result = _tmp0_;
	return result;
}


void haste_applet_automatic_scroll_box_set_max_height (HasteAppletAutomaticScrollBox* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_max_height = _tmp0_;
	g_object_notify ((GObject *) self, "max-height");
}


static void _gtk_widget_queue_resize_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	gtk_widget_queue_resize ((GtkWidget*) self);
}


static GObject * haste_applet_automatic_scroll_box_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	HasteAppletAutomaticScrollBox * self;
	parent_class = G_OBJECT_CLASS (haste_applet_automatic_scroll_box_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBox);
	g_signal_connect_object ((GObject*) self, "notify::max-height", (GCallback) _gtk_widget_queue_resize_g_object_notify, (GtkWidget*) self, 0);
	return obj;
}


static void haste_applet_automatic_scroll_box_class_init (HasteAppletAutomaticScrollBoxClass * klass) {
	haste_applet_automatic_scroll_box_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HasteAppletAutomaticScrollBoxPrivate));
	((GtkWidgetClass *) klass)->get_preferred_height_for_width = haste_applet_automatic_scroll_box_real_get_preferred_height_for_width;
	((GtkWidgetClass *) klass)->get_preferred_height = haste_applet_automatic_scroll_box_real_get_preferred_height;
	G_OBJECT_CLASS (klass)->get_property = _vala_haste_applet_automatic_scroll_box_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_haste_applet_automatic_scroll_box_set_property;
	G_OBJECT_CLASS (klass)->constructor = haste_applet_automatic_scroll_box_constructor;
	G_OBJECT_CLASS (klass)->finalize = haste_applet_automatic_scroll_box_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), HASTE_APPLET_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT, g_param_spec_int ("max-height", "max-height", "max-height", G_MININT, G_MAXINT, 512, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void haste_applet_automatic_scroll_box_instance_init (HasteAppletAutomaticScrollBox * self) {
	self->priv = HASTE_APPLET_AUTOMATIC_SCROLL_BOX_GET_PRIVATE (self);
	self->priv->_max_height = 512;
}


static void haste_applet_automatic_scroll_box_finalize (GObject* obj) {
	HasteAppletAutomaticScrollBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBox);
	G_OBJECT_CLASS (haste_applet_automatic_scroll_box_parent_class)->finalize (obj);
}


GType haste_applet_automatic_scroll_box_get_type (void) {
	return haste_applet_automatic_scroll_box_type_id;
}


GType haste_applet_automatic_scroll_box_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (HasteAppletAutomaticScrollBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) haste_applet_automatic_scroll_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HasteAppletAutomaticScrollBox), 0, (GInstanceInitFunc) haste_applet_automatic_scroll_box_instance_init, NULL };
	haste_applet_automatic_scroll_box_type_id = g_type_module_register_type (module, gtk_scrolled_window_get_type (), "HasteAppletAutomaticScrollBox", &g_define_type_info, 0);
	return haste_applet_automatic_scroll_box_type_id;
}


static void _vala_haste_applet_automatic_scroll_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	HasteAppletAutomaticScrollBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBox);
	switch (property_id) {
		case HASTE_APPLET_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT:
		g_value_set_int (value, haste_applet_automatic_scroll_box_get_max_height (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_haste_applet_automatic_scroll_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	HasteAppletAutomaticScrollBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HASTE_APPLET_TYPE_AUTOMATIC_SCROLL_BOX, HasteAppletAutomaticScrollBox);
	switch (property_id) {
		case HASTE_APPLET_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT:
		haste_applet_automatic_scroll_box_set_max_height (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



