/* HasteApplet.c generated by valac 0.32.1, the Vala compiler
 * generated from HasteApplet.vala, do not modify */

/*
 * This file is part of haste-applet
 *
 * Copyright (C) 2016 Stefan Ric <stfric369@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <glib.h>
#include <glib-object.h>
#include <plugin.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <libpeas/peas.h>


#define HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET (haste_applet_budgie_haste_applet_get_type ())
#define HASTE_APPLET_BUDGIE_HASTE_APPLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET, HasteAppletBudgieHasteApplet))
#define HASTE_APPLET_BUDGIE_HASTE_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET, HasteAppletBudgieHasteAppletClass))
#define HASTE_APPLET_IS_BUDGIE_HASTE_APPLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET))
#define HASTE_APPLET_IS_BUDGIE_HASTE_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET))
#define HASTE_APPLET_BUDGIE_HASTE_APPLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET, HasteAppletBudgieHasteAppletClass))

typedef struct _HasteAppletBudgieHasteApplet HasteAppletBudgieHasteApplet;
typedef struct _HasteAppletBudgieHasteAppletClass HasteAppletBudgieHasteAppletClass;
typedef struct _HasteAppletBudgieHasteAppletPrivate HasteAppletBudgieHasteAppletPrivate;

#define HASTE_APPLET_TYPE_HASTE_APPLET (haste_applet_haste_applet_get_type ())
#define HASTE_APPLET_HASTE_APPLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteApplet))
#define HASTE_APPLET_HASTE_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteAppletClass))
#define HASTE_APPLET_IS_HASTE_APPLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_HASTE_APPLET))
#define HASTE_APPLET_IS_HASTE_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_HASTE_APPLET))
#define HASTE_APPLET_HASTE_APPLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteAppletClass))

typedef struct _HasteAppletHasteApplet HasteAppletHasteApplet;
typedef struct _HasteAppletHasteAppletClass HasteAppletHasteAppletClass;

#define HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS (haste_applet_haste_applet_settings_get_type ())
#define HASTE_APPLET_HASTE_APPLET_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS, HasteAppletHasteAppletSettings))
#define HASTE_APPLET_HASTE_APPLET_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS, HasteAppletHasteAppletSettingsClass))
#define HASTE_APPLET_IS_HASTE_APPLET_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS))
#define HASTE_APPLET_IS_HASTE_APPLET_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS))
#define HASTE_APPLET_HASTE_APPLET_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS, HasteAppletHasteAppletSettingsClass))

typedef struct _HasteAppletHasteAppletSettings HasteAppletHasteAppletSettings;
typedef struct _HasteAppletHasteAppletSettingsClass HasteAppletHasteAppletSettingsClass;
typedef struct _HasteAppletHasteAppletSettingsPrivate HasteAppletHasteAppletSettingsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _HasteAppletHasteAppletPrivate HasteAppletHasteAppletPrivate;

#define HASTE_APPLET_TYPE_HISTORY_VIEW (haste_applet_history_view_get_type ())
#define HASTE_APPLET_HISTORY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW, HasteAppletHistoryView))
#define HASTE_APPLET_HISTORY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_HISTORY_VIEW, HasteAppletHistoryViewClass))
#define HASTE_APPLET_IS_HISTORY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW))
#define HASTE_APPLET_IS_HISTORY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_HISTORY_VIEW))
#define HASTE_APPLET_HISTORY_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW, HasteAppletHistoryViewClass))

typedef struct _HasteAppletHistoryView HasteAppletHistoryView;
typedef struct _HasteAppletHistoryViewClass HasteAppletHistoryViewClass;

#define HASTE_APPLET_TYPE_NEW_HASTE_VIEW (haste_applet_new_haste_view_get_type ())
#define HASTE_APPLET_NEW_HASTE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteView))
#define HASTE_APPLET_NEW_HASTE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteViewClass))
#define HASTE_APPLET_IS_NEW_HASTE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_NEW_HASTE_VIEW))
#define HASTE_APPLET_IS_NEW_HASTE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_NEW_HASTE_VIEW))
#define HASTE_APPLET_NEW_HASTE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteViewClass))

typedef struct _HasteAppletNewHasteView HasteAppletNewHasteView;
typedef struct _HasteAppletNewHasteViewClass HasteAppletNewHasteViewClass;
typedef struct _HasteAppletNewHasteViewPrivate HasteAppletNewHasteViewPrivate;
typedef struct _HasteAppletHistoryViewPrivate HasteAppletHistoryViewPrivate;
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
typedef struct _HasteAppletHasteAppletEntryHackData HasteAppletHasteAppletEntryHackData;

struct _HasteAppletBudgieHasteApplet {
	GObject parent_instance;
	HasteAppletBudgieHasteAppletPrivate * priv;
};

struct _HasteAppletBudgieHasteAppletClass {
	GObjectClass parent_class;
};

struct _HasteAppletHasteAppletSettings {
	GtkGrid parent_instance;
	HasteAppletHasteAppletSettingsPrivate * priv;
};

struct _HasteAppletHasteAppletSettingsClass {
	GtkGridClass parent_class;
};

struct _HasteAppletHasteAppletSettingsPrivate {
	GtkSwitch* switch_label;
	GtkEntry* entry_address;
	GSettings* settings;
};

struct _Block1Data {
	int _ref_count_;
	HasteAppletHasteAppletSettings* self;
	GSettings* settings;
};

struct _HasteAppletHasteApplet {
	BudgieApplet parent_instance;
	HasteAppletHasteAppletPrivate * priv;
	GSettings* settings;
};

struct _HasteAppletHasteAppletClass {
	BudgieAppletClass parent_class;
};

struct _HasteAppletHasteAppletPrivate {
	GtkPopover* popover;
	GtkEventBox* applet_box;
	BudgiePopoverManager* manager;
	GtkLabel* label;
	GtkStack* stack;
	gchar* _uuid;
	HasteAppletHistoryView* history_view;
	HasteAppletNewHasteView* new_haste_view;
};

struct _HasteAppletNewHasteView {
	GtkGrid parent_instance;
	HasteAppletNewHasteViewPrivate * priv;
	GtkEntry* title_entry;
	GtkTextView* textview;
	GtkButton* post_button;
	HasteAppletHistoryView* history_view;
};

struct _HasteAppletNewHasteViewClass {
	GtkGridClass parent_class;
};

struct _HasteAppletHistoryView {
	GtkBox parent_instance;
	HasteAppletHistoryViewPrivate * priv;
	GtkButton* history_add_button;
};

struct _HasteAppletHistoryViewClass {
	GtkBoxClass parent_class;
};

struct _HasteAppletHasteAppletEntryHackData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	HasteAppletHasteApplet* self;
	GtkStack* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	HasteAppletNewHasteView* _tmp3_;
	GtkEntry* _tmp4_;
};


static gpointer haste_applet_budgie_haste_applet_parent_class = NULL;
static BudgiePluginIface* haste_applet_budgie_haste_applet_budgie_plugin_parent_iface = NULL;
static GType haste_applet_budgie_haste_applet_type_id = 0;
static gpointer haste_applet_haste_applet_settings_parent_class = NULL;
static GType haste_applet_haste_applet_settings_type_id = 0;
static gpointer haste_applet_haste_applet_parent_class = NULL;
static GType haste_applet_haste_applet_type_id = 0;

GType haste_applet_budgie_haste_applet_get_type (void) G_GNUC_CONST;
GType haste_applet_budgie_haste_applet_register_type (GTypeModule * module);
enum  {
	HASTE_APPLET_BUDGIE_HASTE_APPLET_DUMMY_PROPERTY
};
static BudgieApplet* haste_applet_budgie_haste_applet_real_get_panel_widget (BudgiePlugin* base, const gchar* uuid);
HasteAppletHasteApplet* haste_applet_haste_applet_new (const gchar* uuid);
HasteAppletHasteApplet* haste_applet_haste_applet_construct (GType object_type, const gchar* uuid);
GType haste_applet_haste_applet_get_type (void) G_GNUC_CONST;
GType haste_applet_haste_applet_register_type (GTypeModule * module);
HasteAppletBudgieHasteApplet* haste_applet_budgie_haste_applet_new (void);
HasteAppletBudgieHasteApplet* haste_applet_budgie_haste_applet_construct (GType object_type);
GType haste_applet_haste_applet_settings_get_type (void) G_GNUC_CONST;
GType haste_applet_haste_applet_settings_register_type (GTypeModule * module);
#define HASTE_APPLET_HASTE_APPLET_SETTINGS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS, HasteAppletHasteAppletSettingsPrivate))
enum  {
	HASTE_APPLET_HASTE_APPLET_SETTINGS_DUMMY_PROPERTY
};
HasteAppletHasteAppletSettings* haste_applet_haste_applet_settings_new (GSettings* settings);
HasteAppletHasteAppletSettings* haste_applet_haste_applet_settings_construct (GType object_type, GSettings* settings);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
gboolean is_the_url_valid (const gchar* url, gchar** new_url, gchar** protocol);
static void __lambda24_ (Block1Data* _data1_);
static void ___lambda24__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
static void haste_applet_haste_applet_settings_finalize (GObject* obj);
GType haste_applet_history_view_get_type (void) G_GNUC_CONST;
GType haste_applet_history_view_register_type (GTypeModule * module);
GType haste_applet_new_haste_view_get_type (void) G_GNUC_CONST;
GType haste_applet_new_haste_view_register_type (GTypeModule * module);
#define HASTE_APPLET_HASTE_APPLET_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteAppletPrivate))
enum  {
	HASTE_APPLET_HASTE_APPLET_DUMMY_PROPERTY,
	HASTE_APPLET_HASTE_APPLET_UUID
};
static GtkWidget* haste_applet_haste_applet_real_get_settings_ui (BudgieApplet* base);
const gchar* haste_applet_haste_applet_get_uuid (HasteAppletHasteApplet* self);
static gboolean haste_applet_haste_applet_real_supports_settings (BudgieApplet* base);
void haste_applet_haste_applet_on_settings_changed (HasteAppletHasteApplet* self, const gchar* key);
static void _haste_applet_haste_applet_on_settings_changed_g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
HasteAppletNewHasteView* haste_applet_new_haste_view_new (GtkStack* stack);
HasteAppletNewHasteView* haste_applet_new_haste_view_construct (GType object_type, GtkStack* stack);
HasteAppletHistoryView* haste_applet_history_view_new (GSettings* settings, GtkClipboard* clipboard);
HasteAppletHistoryView* haste_applet_history_view_construct (GType object_type, GSettings* settings, GtkClipboard* clipboard);
static void __lambda25_ (HasteAppletHasteApplet* self);
static void ___lambda25__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void haste_applet_haste_applet_entry_hack (HasteAppletHasteApplet* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void haste_applet_haste_applet_entry_hack_finish (HasteAppletHasteApplet* self, GAsyncResult* _res_);
static void _haste_applet_haste_applet_entry_hack_gtk_widget_map (GtkWidget* _sender, gpointer self);
static gboolean __lambda27_ (HasteAppletHasteApplet* self, GdkEventButton* e);
gboolean haste_applet_new_haste_view_get_is_editing (HasteAppletNewHasteView* self);
static gboolean ___lambda27__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
void haste_applet_history_view_update_history (HasteAppletHistoryView* self, gint n, gboolean startup, GAsyncReadyCallback _callback_, gpointer _user_data_);
void haste_applet_history_view_update_history_finish (HasteAppletHistoryView* self, GAsyncResult* _res_);
static void haste_applet_haste_applet_entry_hack_data_free (gpointer _data);
static gboolean haste_applet_haste_applet_entry_hack_co (HasteAppletHasteAppletEntryHackData* _data_);
static gboolean ___lambda26_ (HasteAppletHasteApplet* self);
static gboolean ____lambda26__gsource_func (gpointer self);
gboolean haste_applet_new_haste_view_get_haste_address_invalid (HasteAppletNewHasteView* self);
void haste_applet_new_haste_view_dismiss_error_message (HasteAppletNewHasteView* self);
void haste_applet_new_haste_view_set_haste_address_invalid (HasteAppletNewHasteView* self, gboolean value);
void haste_applet_new_haste_view_set_haste_address (HasteAppletNewHasteView* self, const gchar* value);
void haste_applet_new_haste_view_show_error_message (HasteAppletNewHasteView* self, const gchar* message);
void haste_applet_new_haste_view_set_protocol (HasteAppletNewHasteView* self, const gchar* value);
static void haste_applet_haste_applet_real_update_popovers (BudgieApplet* base, BudgiePopoverManager* manager);
void haste_applet_haste_applet_set_uuid (HasteAppletHasteApplet* self, const gchar* value);
static void haste_applet_haste_applet_finalize (GObject* obj);
static void _vala_haste_applet_haste_applet_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_haste_applet_haste_applet_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
void peas_register_types (GTypeModule* module);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static BudgieApplet* haste_applet_budgie_haste_applet_real_get_panel_widget (BudgiePlugin* base, const gchar* uuid) {
	HasteAppletBudgieHasteApplet * self;
	BudgieApplet* result = NULL;
	const gchar* _tmp0_ = NULL;
	HasteAppletHasteApplet* _tmp1_ = NULL;
	self = (HasteAppletBudgieHasteApplet*) base;
	g_return_val_if_fail (uuid != NULL, NULL);
	_tmp0_ = uuid;
	_tmp1_ = haste_applet_haste_applet_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	result = (BudgieApplet*) _tmp1_;
	return result;
}


HasteAppletBudgieHasteApplet* haste_applet_budgie_haste_applet_construct (GType object_type) {
	HasteAppletBudgieHasteApplet * self = NULL;
	self = (HasteAppletBudgieHasteApplet*) g_object_new (object_type, NULL);
	return self;
}


HasteAppletBudgieHasteApplet* haste_applet_budgie_haste_applet_new (void) {
	return haste_applet_budgie_haste_applet_construct (HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET);
}


static void haste_applet_budgie_haste_applet_class_init (HasteAppletBudgieHasteAppletClass * klass) {
	haste_applet_budgie_haste_applet_parent_class = g_type_class_peek_parent (klass);
}


static void haste_applet_budgie_haste_applet_budgie_plugin_interface_init (BudgiePluginIface * iface) {
	haste_applet_budgie_haste_applet_budgie_plugin_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_panel_widget = (BudgieApplet* (*)(BudgiePlugin*, const gchar*)) haste_applet_budgie_haste_applet_real_get_panel_widget;
}


static void haste_applet_budgie_haste_applet_instance_init (HasteAppletBudgieHasteApplet * self) {
}


GType haste_applet_budgie_haste_applet_get_type (void) {
	return haste_applet_budgie_haste_applet_type_id;
}


GType haste_applet_budgie_haste_applet_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (HasteAppletBudgieHasteAppletClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) haste_applet_budgie_haste_applet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HasteAppletBudgieHasteApplet), 0, (GInstanceInitFunc) haste_applet_budgie_haste_applet_instance_init, NULL };
	static const GInterfaceInfo budgie_plugin_info = { (GInterfaceInitFunc) haste_applet_budgie_haste_applet_budgie_plugin_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	haste_applet_budgie_haste_applet_type_id = g_type_module_register_type (module, G_TYPE_OBJECT, "HasteAppletBudgieHasteApplet", &g_define_type_info, 0);
	g_type_module_add_interface (module, haste_applet_budgie_haste_applet_type_id, budgie_plugin_get_type (), &budgie_plugin_info);
	return haste_applet_budgie_haste_applet_type_id;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		HasteAppletHasteAppletSettings* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->settings);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static void __lambda24_ (Block1Data* _data1_) {
	HasteAppletHasteAppletSettings* self;
	GSettings* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_ = FALSE;
	self = _data1_->self;
	_tmp0_ = _data1_->settings;
	_tmp1_ = g_settings_get_string (_tmp0_, "haste-address");
	_tmp2_ = _tmp1_;
	_tmp3_ = is_the_url_valid (_tmp2_, NULL, NULL);
	_tmp4_ = _tmp3_;
	_g_free0 (_tmp2_);
	if (_tmp4_) {
		GtkEntry* _tmp5_ = NULL;
		GtkEntry* _tmp6_ = NULL;
		GtkStyleContext* _tmp7_ = NULL;
		_tmp5_ = self->priv->entry_address;
		gtk_entry_set_icon_from_icon_name (_tmp5_, GTK_ENTRY_ICON_SECONDARY, NULL);
		_tmp6_ = self->priv->entry_address;
		_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) _tmp6_);
		gtk_style_context_remove_class (_tmp7_, "error");
	} else {
		GtkEntry* _tmp8_ = NULL;
		GtkEntry* _tmp9_ = NULL;
		GtkStyleContext* _tmp10_ = NULL;
		_tmp8_ = self->priv->entry_address;
		gtk_entry_set_icon_from_icon_name (_tmp8_, GTK_ENTRY_ICON_SECONDARY, "dialog-error-symbolic");
		_tmp9_ = self->priv->entry_address;
		_tmp10_ = gtk_widget_get_style_context ((GtkWidget*) _tmp9_);
		gtk_style_context_add_class (_tmp10_, "error");
	}
}


static void ___lambda24__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	__lambda24_ (self);
}


HasteAppletHasteAppletSettings* haste_applet_haste_applet_settings_construct (GType object_type, GSettings* settings) {
	HasteAppletHasteAppletSettings * self = NULL;
	Block1Data* _data1_;
	GSettings* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	GtkEntry* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
	GtkEntry* _tmp4_ = NULL;
	GSettings* _tmp5_ = NULL;
	GSettings* _tmp6_ = NULL;
	GSettings* _tmp7_ = NULL;
	GtkSwitch* _tmp8_ = NULL;
	GSettings* _tmp9_ = NULL;
	GtkEntry* _tmp10_ = NULL;
	GSettings* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	gboolean _tmp15_ = FALSE;
	GSettings* _tmp19_ = NULL;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_tmp0_ = settings;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data1_->settings);
	_data1_->settings = _tmp1_;
	self = (HasteAppletHasteAppletSettings*) g_object_new (object_type, NULL);
	_data1_->self = g_object_ref (self);
	_tmp2_ = self->priv->entry_address;
	gtk_entry_set_input_purpose (_tmp2_, GTK_INPUT_PURPOSE_URL);
	_tmp3_ = self->priv->entry_address;
	gtk_entry_set_icon_activatable (_tmp3_, GTK_ENTRY_ICON_SECONDARY, FALSE);
	_tmp4_ = self->priv->entry_address;
	gtk_entry_set_icon_tooltip_text (_tmp4_, GTK_ENTRY_ICON_SECONDARY, "The URL is invalid.");
	_tmp5_ = _data1_->settings;
	_tmp6_ = _g_object_ref0 (_tmp5_);
	_g_object_unref0 (self->priv->settings);
	self->priv->settings = _tmp6_;
	_tmp7_ = _data1_->settings;
	_tmp8_ = self->priv->switch_label;
	g_settings_bind (_tmp7_, "enable-label", (GObject*) _tmp8_, "active", G_SETTINGS_BIND_DEFAULT);
	_tmp9_ = _data1_->settings;
	_tmp10_ = self->priv->entry_address;
	g_settings_bind (_tmp9_, "haste-address", (GObject*) _tmp10_, "text", G_SETTINGS_BIND_DEFAULT);
	_tmp11_ = _data1_->settings;
	_tmp12_ = g_settings_get_string (_tmp11_, "haste-address");
	_tmp13_ = _tmp12_;
	_tmp14_ = is_the_url_valid (_tmp13_, NULL, NULL);
	_tmp15_ = !_tmp14_;
	_g_free0 (_tmp13_);
	if (_tmp15_) {
		GtkEntry* _tmp16_ = NULL;
		GtkEntry* _tmp17_ = NULL;
		GtkStyleContext* _tmp18_ = NULL;
		_tmp16_ = self->priv->entry_address;
		gtk_entry_set_icon_from_icon_name (_tmp16_, GTK_ENTRY_ICON_SECONDARY, "dialog-error-symbolic");
		_tmp17_ = self->priv->entry_address;
		_tmp18_ = gtk_widget_get_style_context ((GtkWidget*) _tmp17_);
		gtk_style_context_add_class (_tmp18_, "error");
	}
	_tmp19_ = _data1_->settings;
	g_signal_connect_data (_tmp19_, "changed", (GCallback) ___lambda24__g_settings_changed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return self;
}


HasteAppletHasteAppletSettings* haste_applet_haste_applet_settings_new (GSettings* settings) {
	return haste_applet_haste_applet_settings_construct (HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS, settings);
}


static void haste_applet_haste_applet_settings_class_init (HasteAppletHasteAppletSettingsClass * klass) {
	gint HasteAppletHasteAppletSettings_private_offset;
	haste_applet_haste_applet_settings_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HasteAppletHasteAppletSettingsPrivate));
	G_OBJECT_CLASS (klass)->finalize = haste_applet_haste_applet_settings_finalize;
	HasteAppletHasteAppletSettings_private_offset = g_type_class_get_instance_private_offset (klass);
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/com/github/cybre/haste-applet/settings.ui");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "switch_label", FALSE, HasteAppletHasteAppletSettings_private_offset + G_STRUCT_OFFSET (HasteAppletHasteAppletSettingsPrivate, switch_label));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "entry_address", FALSE, HasteAppletHasteAppletSettings_private_offset + G_STRUCT_OFFSET (HasteAppletHasteAppletSettingsPrivate, entry_address));
}


static void haste_applet_haste_applet_settings_instance_init (HasteAppletHasteAppletSettings * self) {
	self->priv = HASTE_APPLET_HASTE_APPLET_SETTINGS_GET_PRIVATE (self);
	gtk_widget_init_template (GTK_WIDGET (self));
}


static void haste_applet_haste_applet_settings_finalize (GObject* obj) {
	HasteAppletHasteAppletSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HASTE_APPLET_TYPE_HASTE_APPLET_SETTINGS, HasteAppletHasteAppletSettings);
	_g_object_unref0 (self->priv->switch_label);
	_g_object_unref0 (self->priv->entry_address);
	_g_object_unref0 (self->priv->settings);
	G_OBJECT_CLASS (haste_applet_haste_applet_settings_parent_class)->finalize (obj);
}


GType haste_applet_haste_applet_settings_get_type (void) {
	return haste_applet_haste_applet_settings_type_id;
}


GType haste_applet_haste_applet_settings_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (HasteAppletHasteAppletSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) haste_applet_haste_applet_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HasteAppletHasteAppletSettings), 0, (GInstanceInitFunc) haste_applet_haste_applet_settings_instance_init, NULL };
	haste_applet_haste_applet_settings_type_id = g_type_module_register_type (module, gtk_grid_get_type (), "HasteAppletHasteAppletSettings", &g_define_type_info, 0);
	return haste_applet_haste_applet_settings_type_id;
}


static GtkWidget* haste_applet_haste_applet_real_get_settings_ui (BudgieApplet* base) {
	HasteAppletHasteApplet * self;
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	GSettings* _tmp2_ = NULL;
	HasteAppletHasteAppletSettings* _tmp3_ = NULL;
	GtkWidget* _tmp4_ = NULL;
	self = (HasteAppletHasteApplet*) base;
	_tmp0_ = self->priv->_uuid;
	_tmp1_ = budgie_applet_get_applet_settings ((BudgieApplet*) self, _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = haste_applet_haste_applet_settings_new (_tmp2_);
	g_object_ref_sink (_tmp3_);
	_tmp4_ = (GtkWidget*) _tmp3_;
	_g_object_unref0 (_tmp2_);
	result = _tmp4_;
	return result;
}


static gboolean haste_applet_haste_applet_real_supports_settings (BudgieApplet* base) {
	HasteAppletHasteApplet * self;
	gboolean result = FALSE;
	self = (HasteAppletHasteApplet*) base;
	result = TRUE;
	return result;
}


static void _haste_applet_haste_applet_on_settings_changed_g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	haste_applet_haste_applet_on_settings_changed ((HasteAppletHasteApplet*) self, key);
}


static void __lambda25_ (HasteAppletHasteApplet* self) {
	GtkStack* _tmp0_ = NULL;
	HasteAppletNewHasteView* _tmp1_ = NULL;
	GtkTextView* _tmp2_ = NULL;
	_tmp0_ = self->priv->stack;
	gtk_stack_set_visible_child_name (_tmp0_, "new_haste_view");
	_tmp1_ = self->priv->new_haste_view;
	_tmp2_ = _tmp1_->textview;
	gtk_widget_grab_focus ((GtkWidget*) _tmp2_);
}


static void ___lambda25__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda25_ ((HasteAppletHasteApplet*) self);
}


static void _haste_applet_haste_applet_entry_hack_gtk_widget_map (GtkWidget* _sender, gpointer self) {
	haste_applet_haste_applet_entry_hack ((HasteAppletHasteApplet*) self, NULL, NULL);
}


static gboolean __lambda27_ (HasteAppletHasteApplet* self, GdkEventButton* e) {
	gboolean result = FALSE;
	GtkPopover* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = self->priv->popover;
	_tmp1_ = gtk_widget_get_visible ((GtkWidget*) _tmp0_);
	if (_tmp1_) {
		GtkPopover* _tmp2_ = NULL;
		_tmp2_ = self->priv->popover;
		gtk_widget_hide ((GtkWidget*) _tmp2_);
	} else {
		gchar* child_name = NULL;
		gchar* _tmp3_ = NULL;
		GdkEventButton* _tmp4_ = NULL;
		guint _tmp5_ = 0U;
		GtkStack* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		BudgiePopoverManager* _tmp16_ = NULL;
		GtkEventBox* _tmp17_ = NULL;
		_tmp3_ = g_strdup ("");
		child_name = _tmp3_;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->button;
		if (_tmp5_ == ((guint) 1)) {
			HasteAppletNewHasteView* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			gboolean _tmp8_ = FALSE;
			_tmp6_ = self->priv->new_haste_view;
			_tmp7_ = haste_applet_new_haste_view_get_is_editing (_tmp6_);
			_tmp8_ = _tmp7_;
			if (_tmp8_) {
				gchar* _tmp9_ = NULL;
				_tmp9_ = g_strdup ("new_haste_view");
				_g_free0 (child_name);
				child_name = _tmp9_;
			} else {
				gchar* _tmp10_ = NULL;
				_tmp10_ = g_strdup ("history_view");
				_g_free0 (child_name);
				child_name = _tmp10_;
			}
		} else {
			GdkEventButton* _tmp11_ = NULL;
			guint _tmp12_ = 0U;
			_tmp11_ = e;
			_tmp12_ = _tmp11_->button;
			if (_tmp12_ == ((guint) 3)) {
				gchar* _tmp13_ = NULL;
				_tmp13_ = g_strdup ("new_haste_view");
				_g_free0 (child_name);
				child_name = _tmp13_;
			} else {
				result = GDK_EVENT_PROPAGATE;
				_g_free0 (child_name);
				return result;
			}
		}
		_tmp14_ = self->priv->stack;
		_tmp15_ = child_name;
		gtk_stack_set_visible_child_name (_tmp14_, _tmp15_);
		_tmp16_ = self->priv->manager;
		_tmp17_ = self->priv->applet_box;
		budgie_popover_manager_show_popover (_tmp16_, (GtkWidget*) _tmp17_);
		_g_free0 (child_name);
	}
	result = GDK_EVENT_STOP;
	return result;
}


static gboolean ___lambda27__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda27_ ((HasteAppletHasteApplet*) self, event);
	return result;
}


HasteAppletHasteApplet* haste_applet_haste_applet_construct (GType object_type, const gchar* uuid) {
	HasteAppletHasteApplet * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GSettings* _tmp2_ = NULL;
	GSettings* _tmp3_ = NULL;
	GdkDisplay* display = NULL;
	GdkDisplay* _tmp4_ = NULL;
	GdkDisplay* _tmp5_ = NULL;
	GtkClipboard* clipboard = NULL;
	GdkDisplay* _tmp6_ = NULL;
	GtkClipboard* _tmp7_ = NULL;
	GtkClipboard* _tmp8_ = NULL;
	GdkScreen* screen = NULL;
	GdkScreen* _tmp9_ = NULL;
	GdkScreen* _tmp10_ = NULL;
	GtkSettings* gtk_settings = NULL;
	GdkScreen* _tmp11_ = NULL;
	GtkSettings* _tmp12_ = NULL;
	GtkSettings* _tmp13_ = NULL;
	gchar* gtk_theme_name = NULL;
	GtkSettings* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	gboolean _tmp21_ = FALSE;
	GtkImage* icon = NULL;
	GtkImage* _tmp26_ = NULL;
	GtkLabel* _tmp27_ = NULL;
	GtkLabel* _tmp28_ = NULL;
	GtkBox* layout = NULL;
	GtkBox* _tmp29_ = NULL;
	GtkBox* _tmp30_ = NULL;
	GtkImage* _tmp31_ = NULL;
	GtkBox* _tmp32_ = NULL;
	GtkLabel* _tmp33_ = NULL;
	GtkEventBox* _tmp34_ = NULL;
	GtkEventBox* _tmp35_ = NULL;
	GtkBox* _tmp36_ = NULL;
	GtkStack* _tmp37_ = NULL;
	GtkStack* _tmp38_ = NULL;
	GtkStack* _tmp39_ = NULL;
	HasteAppletNewHasteView* _tmp40_ = NULL;
	GSettings* _tmp41_ = NULL;
	GtkClipboard* _tmp42_ = NULL;
	HasteAppletHistoryView* _tmp43_ = NULL;
	HasteAppletNewHasteView* _tmp44_ = NULL;
	HasteAppletHistoryView* _tmp45_ = NULL;
	HasteAppletHistoryView* _tmp46_ = NULL;
	HasteAppletHistoryView* _tmp47_ = NULL;
	GtkButton* _tmp48_ = NULL;
	GtkStack* _tmp49_ = NULL;
	HasteAppletHistoryView* _tmp50_ = NULL;
	GtkStack* _tmp51_ = NULL;
	HasteAppletNewHasteView* _tmp52_ = NULL;
	GtkStack* _tmp53_ = NULL;
	GtkStack* _tmp54_ = NULL;
	GtkEventBox* _tmp55_ = NULL;
	GtkPopover* _tmp56_ = NULL;
	GtkPopover* _tmp57_ = NULL;
	GtkStyleContext* _tmp58_ = NULL;
	GtkPopover* _tmp59_ = NULL;
	GtkStack* _tmp60_ = NULL;
	GtkPopover* _tmp61_ = NULL;
	GtkEventBox* _tmp62_ = NULL;
	GVariant* history_list = NULL;
	GSettings* _tmp63_ = NULL;
	GVariant* _tmp64_ = NULL;
	GtkEventBox* _tmp72_ = NULL;
	g_return_val_if_fail (uuid != NULL, NULL);
	_tmp0_ = uuid;
	self = (HasteAppletHasteApplet*) g_object_new (object_type, "uuid", _tmp0_, NULL);
	budgie_applet_set_settings_schema ((BudgieApplet*) self, "com.github.cybre.haste-applet");
	budgie_applet_set_settings_prefix ((BudgieApplet*) self, "/com/github/cybre/haste-applet");
	_tmp1_ = uuid;
	_tmp2_ = budgie_applet_get_applet_settings ((BudgieApplet*) self, _tmp1_);
	_g_object_unref0 (self->settings);
	self->settings = _tmp2_;
	_tmp3_ = self->settings;
	g_signal_connect_object (_tmp3_, "changed", (GCallback) _haste_applet_haste_applet_on_settings_changed_g_settings_changed, self, 0);
	_tmp4_ = gtk_widget_get_display ((GtkWidget*) self);
	_tmp5_ = _g_object_ref0 (_tmp4_);
	display = _tmp5_;
	_tmp6_ = display;
	_tmp7_ = gtk_clipboard_get_for_display (_tmp6_, GDK_SELECTION_CLIPBOARD);
	_tmp8_ = _g_object_ref0 (_tmp7_);
	clipboard = _tmp8_;
	_tmp9_ = gdk_screen_get_default ();
	_tmp10_ = _g_object_ref0 (_tmp9_);
	screen = _tmp10_;
	_tmp11_ = screen;
	_tmp12_ = gtk_settings_get_for_screen (_tmp11_);
	_tmp13_ = _g_object_ref0 (_tmp12_);
	gtk_settings = _tmp13_;
	_tmp14_ = gtk_settings;
	g_object_get (_tmp14_, "gtk-theme-name", &_tmp15_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = _tmp16_;
	_tmp18_ = g_utf8_strdown (_tmp17_, (gssize) -1);
	_tmp19_ = _tmp18_;
	_g_free0 (_tmp17_);
	gtk_theme_name = _tmp19_;
	_tmp20_ = gtk_theme_name;
	_tmp21_ = g_str_has_prefix (_tmp20_, "arc");
	if (_tmp21_) {
		GtkCssProvider* provider = NULL;
		GtkCssProvider* _tmp22_ = NULL;
		GtkCssProvider* _tmp23_ = NULL;
		GdkScreen* _tmp24_ = NULL;
		GtkCssProvider* _tmp25_ = NULL;
		_tmp22_ = gtk_css_provider_new ();
		provider = _tmp22_;
		_tmp23_ = provider;
		gtk_css_provider_load_from_resource (_tmp23_, "/com/github/cybre/haste-applet/style.css");
		_tmp24_ = screen;
		_tmp25_ = provider;
		gtk_style_context_add_provider_for_screen (_tmp24_, (GtkStyleProvider*) _tmp25_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
		_g_object_unref0 (provider);
	}
	_tmp26_ = (GtkImage*) gtk_image_new_from_icon_name ("edit-paste-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp26_);
	icon = _tmp26_;
	_tmp27_ = (GtkLabel*) gtk_label_new ("Haste");
	g_object_ref_sink (_tmp27_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp27_;
	_tmp28_ = self->priv->label;
	gtk_widget_set_halign ((GtkWidget*) _tmp28_, GTK_ALIGN_START);
	_tmp29_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp29_);
	layout = _tmp29_;
	_tmp30_ = layout;
	_tmp31_ = icon;
	gtk_box_pack_start (_tmp30_, (GtkWidget*) _tmp31_, FALSE, FALSE, (guint) 3);
	_tmp32_ = layout;
	_tmp33_ = self->priv->label;
	gtk_box_pack_start (_tmp32_, (GtkWidget*) _tmp33_, TRUE, TRUE, (guint) 3);
	_tmp34_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp34_);
	_g_object_unref0 (self->priv->applet_box);
	self->priv->applet_box = _tmp34_;
	_tmp35_ = self->priv->applet_box;
	_tmp36_ = layout;
	gtk_container_add ((GtkContainer*) _tmp35_, (GtkWidget*) _tmp36_);
	_tmp37_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp37_);
	_g_object_unref0 (self->priv->stack);
	self->priv->stack = _tmp37_;
	_tmp38_ = self->priv->stack;
	gtk_stack_set_transition_type (_tmp38_, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT);
	_tmp39_ = self->priv->stack;
	_tmp40_ = haste_applet_new_haste_view_new (_tmp39_);
	g_object_ref_sink (_tmp40_);
	_g_object_unref0 (self->priv->new_haste_view);
	self->priv->new_haste_view = _tmp40_;
	_tmp41_ = self->settings;
	_tmp42_ = clipboard;
	_tmp43_ = haste_applet_history_view_new (_tmp41_, _tmp42_);
	g_object_ref_sink (_tmp43_);
	_g_object_unref0 (self->priv->history_view);
	self->priv->history_view = _tmp43_;
	_tmp44_ = self->priv->new_haste_view;
	_tmp45_ = self->priv->history_view;
	_tmp46_ = _g_object_ref0 (_tmp45_);
	_g_object_unref0 (_tmp44_->history_view);
	_tmp44_->history_view = _tmp46_;
	_tmp47_ = self->priv->history_view;
	_tmp48_ = _tmp47_->history_add_button;
	g_signal_connect_object (_tmp48_, "clicked", (GCallback) ___lambda25__gtk_button_clicked, self, 0);
	_tmp49_ = self->priv->stack;
	_tmp50_ = self->priv->history_view;
	gtk_stack_add_named (_tmp49_, (GtkWidget*) _tmp50_, "history_view");
	_tmp51_ = self->priv->stack;
	_tmp52_ = self->priv->new_haste_view;
	gtk_stack_add_named (_tmp51_, (GtkWidget*) _tmp52_, "new_haste_view");
	_tmp53_ = self->priv->stack;
	gtk_stack_set_homogeneous (_tmp53_, FALSE);
	_tmp54_ = self->priv->stack;
	gtk_widget_show_all ((GtkWidget*) _tmp54_);
	_tmp55_ = self->priv->applet_box;
	_tmp56_ = (GtkPopover*) gtk_popover_new ((GtkWidget*) _tmp55_);
	g_object_ref_sink (_tmp56_);
	_g_object_unref0 (self->priv->popover);
	self->priv->popover = _tmp56_;
	_tmp57_ = self->priv->popover;
	_tmp58_ = gtk_widget_get_style_context ((GtkWidget*) _tmp57_);
	gtk_style_context_add_class (_tmp58_, "haste-applet");
	_tmp59_ = self->priv->popover;
	_tmp60_ = self->priv->stack;
	gtk_container_add ((GtkContainer*) _tmp59_, (GtkWidget*) _tmp60_);
	_tmp61_ = self->priv->popover;
	g_signal_connect_object ((GtkWidget*) _tmp61_, "map", (GCallback) _haste_applet_haste_applet_entry_hack_gtk_widget_map, self, 0);
	_tmp62_ = self->priv->applet_box;
	g_signal_connect_object ((GtkWidget*) _tmp62_, "button-press-event", (GCallback) ___lambda27__gtk_widget_button_press_event, self, 0);
	_tmp63_ = self->settings;
	_tmp64_ = g_settings_get_value (_tmp63_, "history");
	history_list = _tmp64_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp65_ = FALSE;
			_tmp65_ = TRUE;
			while (TRUE) {
				gint _tmp67_ = 0;
				GVariant* _tmp68_ = NULL;
				gsize _tmp69_ = 0UL;
				HasteAppletHistoryView* _tmp70_ = NULL;
				gint _tmp71_ = 0;
				if (!_tmp65_) {
					gint _tmp66_ = 0;
					_tmp66_ = i;
					i = _tmp66_ + 1;
				}
				_tmp65_ = FALSE;
				_tmp67_ = i;
				_tmp68_ = history_list;
				_tmp69_ = g_variant_n_children (_tmp68_);
				if (!(((gsize) _tmp67_) < _tmp69_)) {
					break;
				}
				_tmp70_ = self->priv->history_view;
				_tmp71_ = i;
				haste_applet_history_view_update_history (_tmp70_, _tmp71_, TRUE, NULL, NULL);
			}
		}
	}
	_tmp72_ = self->priv->applet_box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp72_);
	gtk_widget_show_all ((GtkWidget*) self);
	haste_applet_haste_applet_on_settings_changed (self, "enable-label");
	haste_applet_haste_applet_on_settings_changed (self, "haste-address");
	_g_variant_unref0 (history_list);
	_g_object_unref0 (layout);
	_g_object_unref0 (icon);
	_g_free0 (gtk_theme_name);
	_g_object_unref0 (gtk_settings);
	_g_object_unref0 (screen);
	_g_object_unref0 (clipboard);
	_g_object_unref0 (display);
	return self;
}


HasteAppletHasteApplet* haste_applet_haste_applet_new (const gchar* uuid) {
	return haste_applet_haste_applet_construct (HASTE_APPLET_TYPE_HASTE_APPLET, uuid);
}


static void haste_applet_haste_applet_entry_hack_data_free (gpointer _data) {
	HasteAppletHasteAppletEntryHackData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (HasteAppletHasteAppletEntryHackData, _data_);
}


static void haste_applet_haste_applet_entry_hack (HasteAppletHasteApplet* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	HasteAppletHasteAppletEntryHackData* _data_;
	HasteAppletHasteApplet* _tmp0_ = NULL;
	_data_ = g_slice_new0 (HasteAppletHasteAppletEntryHackData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, haste_applet_haste_applet_entry_hack);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, haste_applet_haste_applet_entry_hack_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	haste_applet_haste_applet_entry_hack_co (_data_);
}


static void haste_applet_haste_applet_entry_hack_finish (HasteAppletHasteApplet* self, GAsyncResult* _res_) {
	HasteAppletHasteAppletEntryHackData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean ___lambda26_ (HasteAppletHasteApplet* self) {
	gboolean result = FALSE;
	HasteAppletNewHasteView* _tmp0_ = NULL;
	GtkEntry* _tmp1_ = NULL;
	_tmp0_ = self->priv->new_haste_view;
	_tmp1_ = _tmp0_->title_entry;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp1_, TRUE);
	result = FALSE;
	return result;
}


static gboolean ____lambda26__gsource_func (gpointer self) {
	gboolean result;
	result = ___lambda26_ ((HasteAppletHasteApplet*) self);
	return result;
}


static gboolean haste_applet_haste_applet_entry_hack_co (HasteAppletHasteAppletEntryHackData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = NULL;
	_data_->_tmp0_ = _data_->self->priv->stack;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = gtk_stack_get_visible_child_name (_data_->_tmp0_);
	_data_->_tmp2_ = NULL;
	_data_->_tmp2_ = _data_->_tmp1_;
	if (g_strcmp0 (_data_->_tmp2_, "new_haste_view") == 0) {
		_data_->_tmp3_ = NULL;
		_data_->_tmp3_ = _data_->self->priv->new_haste_view;
		_data_->_tmp4_ = NULL;
		_data_->_tmp4_ = _data_->_tmp3_->title_entry;
		gtk_widget_set_can_focus ((GtkWidget*) _data_->_tmp4_, FALSE);
		g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1, ____lambda26__gsource_func, g_object_ref (_data_->self), g_object_unref);
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


void haste_applet_haste_applet_on_settings_changed (HasteAppletHasteApplet* self, const gchar* key) {
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (key != NULL);
	_tmp0_ = key;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("enable-label")))) {
		switch (0) {
			default:
			{
				GtkLabel* _tmp4_ = NULL;
				GSettings* _tmp5_ = NULL;
				const gchar* _tmp6_ = NULL;
				gboolean _tmp7_ = FALSE;
				_tmp4_ = self->priv->label;
				_tmp5_ = self->settings;
				_tmp6_ = key;
				_tmp7_ = g_settings_get_boolean (_tmp5_, _tmp6_);
				gtk_widget_set_visible ((GtkWidget*) _tmp4_, _tmp7_);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("haste-address")))) {
		switch (0) {
			default:
			{
				gchar* new_url = NULL;
				gchar* protocol = NULL;
				GSettings* _tmp8_ = NULL;
				const gchar* _tmp9_ = NULL;
				gchar* _tmp10_ = NULL;
				gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				gchar* _tmp13_ = NULL;
				gboolean _tmp14_ = FALSE;
				gboolean _tmp15_ = FALSE;
				protocol = NULL;
				_tmp8_ = self->settings;
				_tmp9_ = key;
				_tmp10_ = g_settings_get_string (_tmp8_, _tmp9_);
				_tmp11_ = _tmp10_;
				_tmp14_ = is_the_url_valid (_tmp11_, &_tmp12_, &_tmp13_);
				_g_free0 (new_url);
				new_url = _tmp12_;
				_g_free0 (protocol);
				protocol = _tmp13_;
				_tmp15_ = _tmp14_;
				_g_free0 (_tmp11_);
				if (_tmp15_) {
					HasteAppletNewHasteView* _tmp16_ = NULL;
					gboolean _tmp17_ = FALSE;
					gboolean _tmp18_ = FALSE;
					gboolean _tmp23_ = FALSE;
					const gchar* _tmp24_ = NULL;
					HasteAppletNewHasteView* _tmp29_ = NULL;
					const gchar* _tmp30_ = NULL;
					_tmp16_ = self->priv->new_haste_view;
					_tmp17_ = haste_applet_new_haste_view_get_haste_address_invalid (_tmp16_);
					_tmp18_ = _tmp17_;
					if (_tmp18_) {
						HasteAppletNewHasteView* _tmp19_ = NULL;
						HasteAppletNewHasteView* _tmp20_ = NULL;
						GtkButton* _tmp21_ = NULL;
						HasteAppletNewHasteView* _tmp22_ = NULL;
						_tmp19_ = self->priv->new_haste_view;
						haste_applet_new_haste_view_dismiss_error_message (_tmp19_);
						_tmp20_ = self->priv->new_haste_view;
						_tmp21_ = _tmp20_->post_button;
						gtk_widget_set_sensitive ((GtkWidget*) _tmp21_, TRUE);
						_tmp22_ = self->priv->new_haste_view;
						haste_applet_new_haste_view_set_haste_address_invalid (_tmp22_, FALSE);
					}
					_tmp24_ = protocol;
					if (_tmp24_ != NULL) {
						const gchar* _tmp25_ = NULL;
						_tmp25_ = protocol;
						_tmp23_ = g_strcmp0 (_tmp25_, "") != 0;
					} else {
						_tmp23_ = FALSE;
					}
					if (_tmp23_) {
						GSettings* _tmp26_ = NULL;
						const gchar* _tmp27_ = NULL;
						_tmp26_ = self->settings;
						_tmp27_ = protocol;
						g_settings_set_string (_tmp26_, "protocol", _tmp27_);
					} else {
						GSettings* _tmp28_ = NULL;
						_tmp28_ = self->settings;
						g_settings_set_string (_tmp28_, "protocol", "http");
					}
					_tmp29_ = self->priv->new_haste_view;
					_tmp30_ = new_url;
					haste_applet_new_haste_view_set_haste_address (_tmp29_, _tmp30_);
				} else {
					HasteAppletNewHasteView* _tmp31_ = NULL;
					gboolean _tmp32_ = FALSE;
					gboolean _tmp33_ = FALSE;
					_tmp31_ = self->priv->new_haste_view;
					_tmp32_ = haste_applet_new_haste_view_get_haste_address_invalid (_tmp31_);
					_tmp33_ = _tmp32_;
					if (!_tmp33_) {
						HasteAppletNewHasteView* _tmp34_ = NULL;
						HasteAppletNewHasteView* _tmp35_ = NULL;
						GtkButton* _tmp36_ = NULL;
						HasteAppletNewHasteView* _tmp37_ = NULL;
						_tmp34_ = self->priv->new_haste_view;
						haste_applet_new_haste_view_show_error_message (_tmp34_, "Invalid haste-server Address");
						_tmp35_ = self->priv->new_haste_view;
						_tmp36_ = _tmp35_->post_button;
						gtk_widget_set_sensitive ((GtkWidget*) _tmp36_, FALSE);
						_tmp37_ = self->priv->new_haste_view;
						haste_applet_new_haste_view_set_haste_address_invalid (_tmp37_, TRUE);
					}
				}
				_g_free0 (protocol);
				_g_free0 (new_url);
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("protocol")))) {
		switch (0) {
			default:
			{
				HasteAppletNewHasteView* _tmp38_ = NULL;
				GSettings* _tmp39_ = NULL;
				const gchar* _tmp40_ = NULL;
				gchar* _tmp41_ = NULL;
				gchar* _tmp42_ = NULL;
				_tmp38_ = self->priv->new_haste_view;
				_tmp39_ = self->settings;
				_tmp40_ = key;
				_tmp41_ = g_settings_get_string (_tmp39_, _tmp40_);
				_tmp42_ = _tmp41_;
				haste_applet_new_haste_view_set_protocol (_tmp38_, _tmp42_);
				_g_free0 (_tmp42_);
				break;
			}
		}
	} else {
		switch (0) {
			default:
			{
				break;
			}
		}
	}
}


static void haste_applet_haste_applet_real_update_popovers (BudgieApplet* base, BudgiePopoverManager* manager) {
	HasteAppletHasteApplet * self;
	BudgiePopoverManager* _tmp0_ = NULL;
	GtkEventBox* _tmp1_ = NULL;
	GtkPopover* _tmp2_ = NULL;
	BudgiePopoverManager* _tmp3_ = NULL;
	self = (HasteAppletHasteApplet*) base;
	_tmp0_ = manager;
	_tmp1_ = self->priv->applet_box;
	_tmp2_ = self->priv->popover;
	budgie_popover_manager_register_popover (_tmp0_, (GtkWidget*) _tmp1_, _tmp2_);
	_tmp3_ = manager;
	self->priv->manager = _tmp3_;
}


const gchar* haste_applet_haste_applet_get_uuid (HasteAppletHasteApplet* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_uuid;
	result = _tmp0_;
	return result;
}


void haste_applet_haste_applet_set_uuid (HasteAppletHasteApplet* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_uuid);
	self->priv->_uuid = _tmp1_;
	g_object_notify ((GObject *) self, "uuid");
}


static void haste_applet_haste_applet_class_init (HasteAppletHasteAppletClass * klass) {
	haste_applet_haste_applet_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HasteAppletHasteAppletPrivate));
	((BudgieAppletClass *) klass)->get_settings_ui = haste_applet_haste_applet_real_get_settings_ui;
	((BudgieAppletClass *) klass)->supports_settings = haste_applet_haste_applet_real_supports_settings;
	((BudgieAppletClass *) klass)->update_popovers = haste_applet_haste_applet_real_update_popovers;
	G_OBJECT_CLASS (klass)->get_property = _vala_haste_applet_haste_applet_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_haste_applet_haste_applet_set_property;
	G_OBJECT_CLASS (klass)->finalize = haste_applet_haste_applet_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), HASTE_APPLET_HASTE_APPLET_UUID, g_param_spec_string ("uuid", "uuid", "uuid", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void haste_applet_haste_applet_instance_init (HasteAppletHasteApplet * self) {
	self->priv = HASTE_APPLET_HASTE_APPLET_GET_PRIVATE (self);
	self->priv->popover = NULL;
	self->priv->applet_box = NULL;
	self->priv->manager = NULL;
}


static void haste_applet_haste_applet_finalize (GObject* obj) {
	HasteAppletHasteApplet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteApplet);
	_g_object_unref0 (self->priv->popover);
	_g_object_unref0 (self->priv->applet_box);
	_g_object_unref0 (self->settings);
	_g_object_unref0 (self->priv->label);
	_g_object_unref0 (self->priv->stack);
	_g_free0 (self->priv->_uuid);
	_g_object_unref0 (self->priv->history_view);
	_g_object_unref0 (self->priv->new_haste_view);
	G_OBJECT_CLASS (haste_applet_haste_applet_parent_class)->finalize (obj);
}


GType haste_applet_haste_applet_get_type (void) {
	return haste_applet_haste_applet_type_id;
}


GType haste_applet_haste_applet_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (HasteAppletHasteAppletClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) haste_applet_haste_applet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HasteAppletHasteApplet), 0, (GInstanceInitFunc) haste_applet_haste_applet_instance_init, NULL };
	haste_applet_haste_applet_type_id = g_type_module_register_type (module, budgie_applet_get_type (), "HasteAppletHasteApplet", &g_define_type_info, 0);
	return haste_applet_haste_applet_type_id;
}


static void _vala_haste_applet_haste_applet_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	HasteAppletHasteApplet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteApplet);
	switch (property_id) {
		case HASTE_APPLET_HASTE_APPLET_UUID:
		g_value_set_string (value, haste_applet_haste_applet_get_uuid (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_haste_applet_haste_applet_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	HasteAppletHasteApplet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HASTE_APPLET_TYPE_HASTE_APPLET, HasteAppletHasteApplet);
	switch (property_id) {
		case HASTE_APPLET_HASTE_APPLET_UUID:
		haste_applet_haste_applet_set_uuid (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static gboolean string_contains (const gchar* self, const gchar* needle) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = needle;
	_tmp1_ = strstr ((gchar*) self, (gchar*) _tmp0_);
	result = _tmp1_ != NULL;
	return result;
}


gboolean is_the_url_valid (const gchar* url, gchar** new_url, gchar** protocol) {
	gchar* _vala_new_url = NULL;
	gchar* _vala_protocol = NULL;
	gboolean result = FALSE;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (url != NULL, FALSE);
	_tmp0_ = g_strdup ("");
	_g_free0 (_vala_new_url);
	_vala_new_url = _tmp0_;
	_tmp1_ = url;
	if (g_strcmp0 (_tmp1_, "") != 0) {
		gchar** ha_split = NULL;
		const gchar* _tmp2_ = NULL;
		gchar** _tmp3_ = NULL;
		gchar** _tmp4_ = NULL;
		gint ha_split_length1 = 0;
		gint _ha_split_size_ = 0;
		gchar** _tmp5_ = NULL;
		gint _tmp5__length1 = 0;
		gchar** ha_split2 = NULL;
		gint ha_split2_length1 = 0;
		gint _ha_split2_size_ = 0;
		gchar** _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
		const gchar* _tmp10_ = NULL;
		gchar** ha_split3 = NULL;
		gchar** _tmp19_ = NULL;
		gint _tmp19__length1 = 0;
		const gchar* _tmp20_ = NULL;
		gchar** _tmp21_ = NULL;
		gchar** _tmp22_ = NULL;
		gint ha_split3_length1 = 0;
		gint _ha_split3_size_ = 0;
		gchar** invalid_characters = NULL;
		gchar* _tmp23_ = NULL;
		gchar* _tmp24_ = NULL;
		gchar* _tmp25_ = NULL;
		gchar* _tmp26_ = NULL;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		gchar* _tmp31_ = NULL;
		gchar* _tmp32_ = NULL;
		gchar* _tmp33_ = NULL;
		gchar* _tmp34_ = NULL;
		gchar* _tmp35_ = NULL;
		gchar* _tmp36_ = NULL;
		gchar* _tmp37_ = NULL;
		gchar* _tmp38_ = NULL;
		gchar* _tmp39_ = NULL;
		gchar* _tmp40_ = NULL;
		gchar* _tmp41_ = NULL;
		gchar* _tmp42_ = NULL;
		gchar* _tmp43_ = NULL;
		gchar* _tmp44_ = NULL;
		gchar* _tmp45_ = NULL;
		gchar* _tmp46_ = NULL;
		gchar* _tmp47_ = NULL;
		gchar* _tmp48_ = NULL;
		gchar* _tmp49_ = NULL;
		gchar* _tmp50_ = NULL;
		gchar* _tmp51_ = NULL;
		gchar** _tmp52_ = NULL;
		gint invalid_characters_length1 = 0;
		gint _invalid_characters_size_ = 0;
		gchar** _tmp53_ = NULL;
		gint _tmp53__length1 = 0;
		gchar** _tmp63_ = NULL;
		gint _tmp63__length1 = 0;
		_tmp2_ = url;
		_tmp4_ = _tmp3_ = g_strsplit (_tmp2_, "://", 0);
		ha_split = _tmp4_;
		ha_split_length1 = _vala_array_length (_tmp3_);
		_ha_split_size_ = ha_split_length1;
		_tmp5_ = ha_split;
		_tmp5__length1 = ha_split_length1;
		if (_tmp5__length1 > 1) {
			gchar** _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			const gchar* _tmp7_ = NULL;
			gchar* _tmp8_ = NULL;
			_tmp6_ = ha_split;
			_tmp6__length1 = ha_split_length1;
			_tmp7_ = _tmp6_[0];
			_tmp8_ = g_strdup (_tmp7_);
			_g_free0 (_vala_protocol);
			_vala_protocol = _tmp8_;
		}
		ha_split2 = NULL;
		ha_split2_length1 = 0;
		_ha_split2_size_ = ha_split2_length1;
		_tmp9_ = ha_split;
		_tmp9__length1 = ha_split_length1;
		_tmp10_ = _tmp9_[1];
		if (_tmp10_ != NULL) {
			gchar** _tmp11_ = NULL;
			gint _tmp11__length1 = 0;
			const gchar* _tmp12_ = NULL;
			gchar** _tmp13_ = NULL;
			gchar** _tmp14_ = NULL;
			_tmp11_ = ha_split;
			_tmp11__length1 = ha_split_length1;
			_tmp12_ = _tmp11_[1];
			_tmp14_ = _tmp13_ = g_strsplit (_tmp12_, "/", 0);
			ha_split2 = (_vala_array_free (ha_split2, ha_split2_length1, (GDestroyNotify) g_free), NULL);
			ha_split2 = _tmp14_;
			ha_split2_length1 = _vala_array_length (_tmp13_);
			_ha_split2_size_ = ha_split2_length1;
		} else {
			gchar** _tmp15_ = NULL;
			gint _tmp15__length1 = 0;
			const gchar* _tmp16_ = NULL;
			gchar** _tmp17_ = NULL;
			gchar** _tmp18_ = NULL;
			_tmp15_ = ha_split;
			_tmp15__length1 = ha_split_length1;
			_tmp16_ = _tmp15_[0];
			_tmp18_ = _tmp17_ = g_strsplit (_tmp16_, "/", 0);
			ha_split2 = (_vala_array_free (ha_split2, ha_split2_length1, (GDestroyNotify) g_free), NULL);
			ha_split2 = _tmp18_;
			ha_split2_length1 = _vala_array_length (_tmp17_);
			_ha_split2_size_ = ha_split2_length1;
		}
		_tmp19_ = ha_split2;
		_tmp19__length1 = ha_split2_length1;
		_tmp20_ = _tmp19_[0];
		_tmp22_ = _tmp21_ = g_strsplit (_tmp20_, ".", 0);
		ha_split3 = _tmp22_;
		ha_split3_length1 = _vala_array_length (_tmp21_);
		_ha_split3_size_ = ha_split3_length1;
		_tmp23_ = g_strdup ("`");
		_tmp24_ = g_strdup ("~");
		_tmp25_ = g_strdup ("!");
		_tmp26_ = g_strdup ("@");
		_tmp27_ = g_strdup ("#");
		_tmp28_ = g_strdup ("$");
		_tmp29_ = g_strdup ("%");
		_tmp30_ = g_strdup ("^");
		_tmp31_ = g_strdup ("&");
		_tmp32_ = g_strdup ("*");
		_tmp33_ = g_strdup ("(");
		_tmp34_ = g_strdup (")");
		_tmp35_ = g_strdup ("_");
		_tmp36_ = g_strdup ("=");
		_tmp37_ = g_strdup ("+");
		_tmp38_ = g_strdup ("[");
		_tmp39_ = g_strdup ("]");
		_tmp40_ = g_strdup ("{");
		_tmp41_ = g_strdup ("}");
		_tmp42_ = g_strdup ("\\");
		_tmp43_ = g_strdup ("|");
		_tmp44_ = g_strdup (";");
		_tmp45_ = g_strdup (":");
		_tmp46_ = g_strdup (",");
		_tmp47_ = g_strdup (".");
		_tmp48_ = g_strdup ("<");
		_tmp49_ = g_strdup (">");
		_tmp50_ = g_strdup ("/");
		_tmp51_ = g_strdup ("?");
		_tmp52_ = g_new0 (gchar*, 29 + 1);
		_tmp52_[0] = _tmp23_;
		_tmp52_[1] = _tmp24_;
		_tmp52_[2] = _tmp25_;
		_tmp52_[3] = _tmp26_;
		_tmp52_[4] = _tmp27_;
		_tmp52_[5] = _tmp28_;
		_tmp52_[6] = _tmp29_;
		_tmp52_[7] = _tmp30_;
		_tmp52_[8] = _tmp31_;
		_tmp52_[9] = _tmp32_;
		_tmp52_[10] = _tmp33_;
		_tmp52_[11] = _tmp34_;
		_tmp52_[12] = _tmp35_;
		_tmp52_[13] = _tmp36_;
		_tmp52_[14] = _tmp37_;
		_tmp52_[15] = _tmp38_;
		_tmp52_[16] = _tmp39_;
		_tmp52_[17] = _tmp40_;
		_tmp52_[18] = _tmp41_;
		_tmp52_[19] = _tmp42_;
		_tmp52_[20] = _tmp43_;
		_tmp52_[21] = _tmp44_;
		_tmp52_[22] = _tmp45_;
		_tmp52_[23] = _tmp46_;
		_tmp52_[24] = _tmp47_;
		_tmp52_[25] = _tmp48_;
		_tmp52_[26] = _tmp49_;
		_tmp52_[27] = _tmp50_;
		_tmp52_[28] = _tmp51_;
		invalid_characters = _tmp52_;
		invalid_characters_length1 = 29;
		_invalid_characters_size_ = invalid_characters_length1;
		_tmp53_ = invalid_characters;
		_tmp53__length1 = invalid_characters_length1;
		{
			gchar** character_collection = NULL;
			gint character_collection_length1 = 0;
			gint _character_collection_size_ = 0;
			gint character_it = 0;
			character_collection = _tmp53_;
			character_collection_length1 = _tmp53__length1;
			for (character_it = 0; character_it < _tmp53__length1; character_it = character_it + 1) {
				gchar* _tmp54_ = NULL;
				gchar* character = NULL;
				_tmp54_ = g_strdup (character_collection[character_it]);
				character = _tmp54_;
				{
					gchar** _tmp55_ = NULL;
					gint _tmp55__length1 = 0;
					_tmp55_ = ha_split3;
					_tmp55__length1 = ha_split3_length1;
					{
						gchar** part_collection = NULL;
						gint part_collection_length1 = 0;
						gint _part_collection_size_ = 0;
						gint part_it = 0;
						part_collection = _tmp55_;
						part_collection_length1 = _tmp55__length1;
						for (part_it = 0; part_it < _tmp55__length1; part_it = part_it + 1) {
							gchar* _tmp56_ = NULL;
							gchar* part = NULL;
							_tmp56_ = g_strdup (part_collection[part_it]);
							part = _tmp56_;
							{
								const gchar* _tmp57_ = NULL;
								gint _tmp58_ = 0;
								gint _tmp59_ = 0;
								const gchar* _tmp60_ = NULL;
								const gchar* _tmp61_ = NULL;
								gboolean _tmp62_ = FALSE;
								_tmp57_ = part;
								_tmp58_ = strlen (_tmp57_);
								_tmp59_ = _tmp58_;
								if (_tmp59_ < 2) {
									result = FALSE;
									_g_free0 (part);
									_g_free0 (character);
									invalid_characters = (_vala_array_free (invalid_characters, invalid_characters_length1, (GDestroyNotify) g_free), NULL);
									ha_split3 = (_vala_array_free (ha_split3, ha_split3_length1, (GDestroyNotify) g_free), NULL);
									ha_split2 = (_vala_array_free (ha_split2, ha_split2_length1, (GDestroyNotify) g_free), NULL);
									ha_split = (_vala_array_free (ha_split, ha_split_length1, (GDestroyNotify) g_free), NULL);
									if (new_url) {
										*new_url = _vala_new_url;
									} else {
										_g_free0 (_vala_new_url);
									}
									if (protocol) {
										*protocol = _vala_protocol;
									} else {
										_g_free0 (_vala_protocol);
									}
									return result;
								}
								_tmp60_ = part;
								_tmp61_ = character;
								_tmp62_ = string_contains (_tmp60_, _tmp61_);
								if (_tmp62_) {
									result = FALSE;
									_g_free0 (part);
									_g_free0 (character);
									invalid_characters = (_vala_array_free (invalid_characters, invalid_characters_length1, (GDestroyNotify) g_free), NULL);
									ha_split3 = (_vala_array_free (ha_split3, ha_split3_length1, (GDestroyNotify) g_free), NULL);
									ha_split2 = (_vala_array_free (ha_split2, ha_split2_length1, (GDestroyNotify) g_free), NULL);
									ha_split = (_vala_array_free (ha_split, ha_split_length1, (GDestroyNotify) g_free), NULL);
									if (new_url) {
										*new_url = _vala_new_url;
									} else {
										_g_free0 (_vala_new_url);
									}
									if (protocol) {
										*protocol = _vala_protocol;
									} else {
										_g_free0 (_vala_protocol);
									}
									return result;
								}
								_g_free0 (part);
							}
						}
					}
					_g_free0 (character);
				}
			}
		}
		_tmp63_ = ha_split3;
		_tmp63__length1 = ha_split3_length1;
		if (_tmp63__length1 >= 2) {
			gboolean _tmp64_ = FALSE;
			gchar** _tmp65_ = NULL;
			gint _tmp65__length1 = 0;
			const gchar* _tmp66_ = NULL;
			_tmp65_ = ha_split3;
			_tmp65__length1 = ha_split3_length1;
			_tmp66_ = _tmp65_[0];
			if (g_strcmp0 (_tmp66_, "") != 0) {
				gchar** _tmp67_ = NULL;
				gint _tmp67__length1 = 0;
				gchar** _tmp68_ = NULL;
				gint _tmp68__length1 = 0;
				const gchar* _tmp69_ = NULL;
				_tmp67_ = ha_split3;
				_tmp67__length1 = ha_split3_length1;
				_tmp68_ = ha_split3;
				_tmp68__length1 = ha_split3_length1;
				_tmp69_ = _tmp67_[_tmp68__length1 - 1];
				_tmp64_ = g_strcmp0 (_tmp69_, "") != 0;
			} else {
				_tmp64_ = FALSE;
			}
			if (_tmp64_) {
				gchar** _tmp70_ = NULL;
				gint _tmp70__length1 = 0;
				const gchar* _tmp71_ = NULL;
				gchar* _tmp72_ = NULL;
				_tmp70_ = ha_split2;
				_tmp70__length1 = ha_split2_length1;
				_tmp71_ = _tmp70_[0];
				_tmp72_ = g_strdup (_tmp71_);
				_g_free0 (_vala_new_url);
				_vala_new_url = _tmp72_;
				result = TRUE;
				invalid_characters = (_vala_array_free (invalid_characters, invalid_characters_length1, (GDestroyNotify) g_free), NULL);
				ha_split3 = (_vala_array_free (ha_split3, ha_split3_length1, (GDestroyNotify) g_free), NULL);
				ha_split2 = (_vala_array_free (ha_split2, ha_split2_length1, (GDestroyNotify) g_free), NULL);
				ha_split = (_vala_array_free (ha_split, ha_split_length1, (GDestroyNotify) g_free), NULL);
				if (new_url) {
					*new_url = _vala_new_url;
				} else {
					_g_free0 (_vala_new_url);
				}
				if (protocol) {
					*protocol = _vala_protocol;
				} else {
					_g_free0 (_vala_protocol);
				}
				return result;
			}
		}
		invalid_characters = (_vala_array_free (invalid_characters, invalid_characters_length1, (GDestroyNotify) g_free), NULL);
		ha_split3 = (_vala_array_free (ha_split3, ha_split3_length1, (GDestroyNotify) g_free), NULL);
		ha_split2 = (_vala_array_free (ha_split2, ha_split2_length1, (GDestroyNotify) g_free), NULL);
		ha_split = (_vala_array_free (ha_split, ha_split_length1, (GDestroyNotify) g_free), NULL);
	}
	result = FALSE;
	if (new_url) {
		*new_url = _vala_new_url;
	} else {
		_g_free0 (_vala_new_url);
	}
	if (protocol) {
		*protocol = _vala_protocol;
	} else {
		_g_free0 (_vala_protocol);
	}
	return result;
}


void peas_register_types (GTypeModule* module) {
	PeasObjectModule* objmodule = NULL;
	GTypeModule* _tmp0_ = NULL;
	PeasObjectModule* _tmp1_ = NULL;
	g_return_if_fail (module != NULL);
	haste_applet_budgie_haste_applet_register_type (module);
	haste_applet_haste_applet_settings_register_type (module);
	haste_applet_haste_applet_register_type (module);
	haste_applet_new_haste_view_register_type (module);
	haste_applet_history_view_register_type (module);
	haste_applet_automatic_scroll_box_register_type (module);
	haste_applet_history_view_item_register_type (module);
	_tmp0_ = module;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, peas_object_module_get_type ()) ? ((PeasObjectModule*) _tmp0_) : NULL);
	objmodule = _tmp1_;
	peas_object_module_register_extension_type (objmodule, budgie_plugin_get_type (), HASTE_APPLET_TYPE_BUDGIE_HASTE_APPLET);
	_g_object_unref0 (objmodule);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



