/* HistoryViewItem.c generated by valac 0.32.1, the Vala compiler
 * generated from HistoryViewItem.vala, do not modify */

/*
 * This file is part of haste-applet
 *
 * Copyright (C) 2016 Stefan Ric <stfric369@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM (haste_applet_history_view_item_get_type ())
#define HASTE_APPLET_HISTORY_VIEW_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, HasteAppletHistoryViewItem))
#define HASTE_APPLET_HISTORY_VIEW_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, HasteAppletHistoryViewItemClass))
#define HASTE_APPLET_IS_HISTORY_VIEW_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM))
#define HASTE_APPLET_IS_HISTORY_VIEW_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM))
#define HASTE_APPLET_HISTORY_VIEW_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, HasteAppletHistoryViewItemClass))

typedef struct _HasteAppletHistoryViewItem HasteAppletHistoryViewItem;
typedef struct _HasteAppletHistoryViewItemClass HasteAppletHistoryViewItemClass;
typedef struct _HasteAppletHistoryViewItemPrivate HasteAppletHistoryViewItemPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block5Data Block5Data;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))

struct _HasteAppletHistoryViewItem {
	GtkRevealer parent_instance;
	HasteAppletHistoryViewItemPrivate * priv;
};

struct _HasteAppletHistoryViewItemClass {
	GtkRevealerClass parent_class;
};

struct _HasteAppletHistoryViewItemPrivate {
	GtkLabel* title_label;
	GtkEntry* title_entry;
	gchar* title;
	gchar* url;
	gint64 timestamp;
};

struct _Block5Data {
	int _ref_count_;
	HasteAppletHistoryViewItem* self;
	GDateTime* time;
	GtkStack* title_stack;
	GtkStack* copy_stack;
	GSettings* gnome_settings;
	gchar* time_format;
	gchar* time_text;
	GtkLabel* time_label;
	GSettings* settings;
};


static gpointer haste_applet_history_view_item_parent_class = NULL;
static GType haste_applet_history_view_item_type_id = 0;

GType haste_applet_history_view_item_get_type (void) G_GNUC_CONST;
GType haste_applet_history_view_item_register_type (GTypeModule * module);
#define HASTE_APPLET_HISTORY_VIEW_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, HasteAppletHistoryViewItemPrivate))
enum  {
	HASTE_APPLET_HISTORY_VIEW_ITEM_DUMMY_PROPERTY
};
HasteAppletHistoryViewItem* haste_applet_history_view_item_new (gint n, GSettings* settings);
HasteAppletHistoryViewItem* haste_applet_history_view_item_construct (GType object_type, gint n, GSettings* settings);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
static void __lambda4_ (HasteAppletHistoryViewItem* self);
static void ___lambda4__gtk_entry_icon_press (GtkEntry* _sender, GtkEntryIconPosition p0, GdkEvent* p1, gpointer self);
static gboolean __lambda5_ (HasteAppletHistoryViewItem* self);
static gboolean ___lambda5__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void __lambda6_ (Block5Data* _data5_, const gchar* key);
static void ___lambda6__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self);
static void __lambda7_ (Block5Data* _data5_);
static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda8_ (Block5Data* _data5_);
static void haste_applet_history_view_item_apply_changes (HasteAppletHistoryViewItem* self, GSettings* settings);
static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda9_ (Block5Data* _data5_);
static void ___lambda9__gtk_entry_activate (GtkEntry* _sender, gpointer self);
static gboolean __lambda10_ (Block5Data* _data5_, GdkEventKey* event);
static gboolean ___lambda10__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
static void __lambda11_ (Block5Data* _data5_);
static gboolean __lambda12_ (Block5Data* _data5_);
static gboolean ___lambda12__gsource_func (gpointer self);
static void ___lambda11__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda13_ (Block5Data* _data5_);
static void haste_applet_history_view_item_delete_item (HasteAppletHistoryViewItem* self, GSettings* settings);
static void ___lambda13__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _vala_array_add3 (GVariant*** array, int* length, int* size, GVariant* value);
static void __lambda14_ (HasteAppletHistoryViewItem* self);
static void ___lambda14__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void _vala_array_add4 (GVariant*** array, int* length, int* size, GVariant* value);
static void _vala_array_add5 (GVariant*** array, int* length, int* size, GVariant* value);
static void haste_applet_history_view_item_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static Block5Data* block5_data_ref (Block5Data* _data5_) {
	g_atomic_int_inc (&_data5_->_ref_count_);
	return _data5_;
}


static void block5_data_unref (void * _userdata_) {
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
		HasteAppletHistoryViewItem* self;
		self = _data5_->self;
		_g_object_unref0 (_data5_->time_label);
		_g_free0 (_data5_->time_text);
		_g_free0 (_data5_->time_format);
		_g_object_unref0 (_data5_->gnome_settings);
		_g_object_unref0 (_data5_->copy_stack);
		_g_object_unref0 (_data5_->title_stack);
		_g_date_time_unref0 (_data5_->time);
		_g_object_unref0 (_data5_->settings);
		_g_object_unref0 (self);
		g_slice_free (Block5Data, _data5_);
	}
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static void __lambda4_ (HasteAppletHistoryViewItem* self) {
	GtkEntry* _tmp0_ = NULL;
	_tmp0_ = self->priv->title_entry;
	gtk_entry_set_text (_tmp0_, "");
}


static void ___lambda4__gtk_entry_icon_press (GtkEntry* _sender, GtkEntryIconPosition p0, GdkEvent* p1, gpointer self) {
	__lambda4_ ((HasteAppletHistoryViewItem*) self);
}


static gboolean __lambda5_ (HasteAppletHistoryViewItem* self) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
	{
		GdkScreen* _tmp0_ = NULL;
		const gchar* _tmp1_ = NULL;
		_tmp0_ = gdk_screen_get_default ();
		_tmp1_ = self->priv->url;
		gtk_show_uri (_tmp0_, _tmp1_, (guint32) GDK_CURRENT_TIME, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp2_ = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = stderr;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		fprintf (_tmp2_, "%s", _tmp4_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	result = TRUE;
	return result;
}


static gboolean ___lambda5__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda5_ ((HasteAppletHistoryViewItem*) self);
	return result;
}


static void __lambda6_ (Block5Data* _data5_, const gchar* key) {
	HasteAppletHistoryViewItem* self;
	const gchar* _tmp0_ = NULL;
	self = _data5_->self;
	g_return_if_fail (key != NULL);
	_tmp0_ = key;
	if (g_strcmp0 (_tmp0_, "clock-format") == 0) {
		GSettings* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp1_ = _data5_->gnome_settings;
		_tmp2_ = g_settings_get_string (_tmp1_, "clock-format");
		_g_free0 (_data5_->time_format);
		_data5_->time_format = _tmp2_;
		_tmp4_ = _data5_->time_format;
		if (g_strcmp0 (_tmp4_, "24h") == 0) {
			GDateTime* _tmp5_ = NULL;
			gchar* _tmp6_ = NULL;
			_tmp5_ = _data5_->time;
			_tmp6_ = g_date_time_format (_tmp5_, "%H:%M");
			_g_free0 (_tmp3_);
			_tmp3_ = _tmp6_;
		} else {
			GDateTime* _tmp7_ = NULL;
			gchar* _tmp8_ = NULL;
			_tmp7_ = _data5_->time;
			_tmp8_ = g_date_time_format (_tmp7_, "%l:%M %p");
			_g_free0 (_tmp3_);
			_tmp3_ = _tmp8_;
		}
		_tmp9_ = g_strdup (_tmp3_);
		_g_free0 (_data5_->time_text);
		_data5_->time_text = _tmp9_;
		gtk_label_set_label (_data5_->time_label, _data5_->time_text);
		_g_free0 (_tmp3_);
	}
}


static void ___lambda6__g_settings_changed (GSettings* _sender, const gchar* key, gpointer self) {
	__lambda6_ (self, key);
}


static void __lambda7_ (Block5Data* _data5_) {
	HasteAppletHistoryViewItem* self;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkStack* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
	self = _data5_->self;
	_tmp0_ = self->priv->title_entry;
	_tmp1_ = self->priv->title;
	gtk_entry_set_text (_tmp0_, _tmp1_);
	_tmp2_ = _data5_->title_stack;
	gtk_stack_set_visible_child_name (_tmp2_, "title_edit_box");
	_tmp3_ = self->priv->title_entry;
	gtk_widget_grab_focus ((GtkWidget*) _tmp3_);
}


static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda7_ (self);
}


static void __lambda8_ (Block5Data* _data5_) {
	HasteAppletHistoryViewItem* self;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkStack* _tmp5_ = NULL;
	self = _data5_->self;
	_tmp0_ = self->priv->title_entry;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->title;
	if (g_strcmp0 (_tmp2_, _tmp3_) != 0) {
		GSettings* _tmp4_ = NULL;
		_tmp4_ = _data5_->settings;
		haste_applet_history_view_item_apply_changes (self, _tmp4_);
	}
	_tmp5_ = _data5_->title_stack;
	gtk_stack_set_visible_child_name (_tmp5_, "title_box");
}


static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda8_ (self);
}


static void __lambda9_ (Block5Data* _data5_) {
	HasteAppletHistoryViewItem* self;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkStack* _tmp5_ = NULL;
	self = _data5_->self;
	_tmp0_ = self->priv->title_entry;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->title;
	if (g_strcmp0 (_tmp2_, _tmp3_) != 0) {
		GSettings* _tmp4_ = NULL;
		_tmp4_ = _data5_->settings;
		haste_applet_history_view_item_apply_changes (self, _tmp4_);
	}
	_tmp5_ = _data5_->title_stack;
	gtk_stack_set_visible_child_name (_tmp5_, "title_box");
}


static void ___lambda9__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
	__lambda9_ (self);
}


static gboolean __lambda10_ (Block5Data* _data5_, GdkEventKey* event) {
	HasteAppletHistoryViewItem* self;
	gboolean result = FALSE;
	GdkEventKey* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	self = _data5_->self;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = event;
	_tmp1_ = _tmp0_->keyval;
	if (_tmp1_ == ((guint) GDK_KEY_Escape)) {
		GtkStack* _tmp2_ = NULL;
		_tmp2_ = _data5_->title_stack;
		gtk_stack_set_visible_child_name (_tmp2_, "title_box");
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


static gboolean ___lambda10__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = __lambda10_ (self, event);
	return result;
}


static gboolean __lambda12_ (Block5Data* _data5_) {
	HasteAppletHistoryViewItem* self;
	gboolean result = FALSE;
	GtkStack* _tmp0_ = NULL;
	self = _data5_->self;
	_tmp0_ = _data5_->copy_stack;
	gtk_stack_set_visible_child_name (_tmp0_, "copy_button");
	result = FALSE;
	return result;
}


static gboolean ___lambda12__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda12_ (self);
	return result;
}


static void __lambda11_ (Block5Data* _data5_) {
	HasteAppletHistoryViewItem* self;
	GtkStack* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	self = _data5_->self;
	_tmp0_ = _data5_->copy_stack;
	gtk_stack_set_visible_child_name (_tmp0_, "copy_ok_image");
	_tmp1_ = self->priv->url;
	g_signal_emit_by_name (self, "copy", _tmp1_);
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 500, ___lambda12__gsource_func, block5_data_ref (_data5_), block5_data_unref);
}


static void ___lambda11__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda11_ (self);
}


static void __lambda13_ (Block5Data* _data5_) {
	HasteAppletHistoryViewItem* self;
	GSettings* _tmp0_ = NULL;
	self = _data5_->self;
	_tmp0_ = _data5_->settings;
	haste_applet_history_view_item_delete_item (self, _tmp0_);
}


static void ___lambda13__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda13_ (self);
}


HasteAppletHistoryViewItem* haste_applet_history_view_item_construct (GType object_type, gint n, GSettings* settings) {
	HasteAppletHistoryViewItem * self = NULL;
	Block5Data* _data5_;
	GSettings* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	GVariant* history_list = NULL;
	GSettings* _tmp2_ = NULL;
	GVariant* _tmp3_ = NULL;
	GVariant* history_entry = NULL;
	GVariant* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GVariant* _tmp6_ = NULL;
	GVariant* _tmp7_ = NULL;
	gint64 _tmp8_ = 0LL;
	GDateTime* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	GtkLabel* _tmp17_ = NULL;
	GtkLabel* _tmp18_ = NULL;
	GtkLabel* _tmp19_ = NULL;
	GtkLabel* _tmp20_ = NULL;
	GtkLabel* _tmp21_ = NULL;
	GtkButton* title_edit_button = NULL;
	GtkButton* _tmp22_ = NULL;
	GtkButton* _tmp23_ = NULL;
	GtkButton* _tmp24_ = NULL;
	GtkButton* _tmp25_ = NULL;
	GtkButton* _tmp26_ = NULL;
	GtkStyleContext* _tmp27_ = NULL;
	GtkBox* title_box = NULL;
	GtkBox* _tmp28_ = NULL;
	GtkBox* _tmp29_ = NULL;
	GtkLabel* _tmp30_ = NULL;
	GtkBox* _tmp31_ = NULL;
	GtkButton* _tmp32_ = NULL;
	GtkEntry* _tmp33_ = NULL;
	GtkEntry* _tmp34_ = NULL;
	GtkEntry* _tmp35_ = NULL;
	GtkEntry* _tmp36_ = NULL;
	GtkEntry* _tmp37_ = NULL;
	GtkEntry* _tmp38_ = NULL;
	GtkEntry* _tmp39_ = NULL;
	GtkButton* title_apply_button = NULL;
	GtkButton* _tmp40_ = NULL;
	GtkButton* _tmp41_ = NULL;
	GtkButton* _tmp42_ = NULL;
	GtkButton* _tmp43_ = NULL;
	GtkButton* _tmp44_ = NULL;
	GtkStyleContext* _tmp45_ = NULL;
	GtkBox* title_edit_box = NULL;
	GtkBox* _tmp46_ = NULL;
	GtkBox* _tmp47_ = NULL;
	GtkEntry* _tmp48_ = NULL;
	GtkBox* _tmp49_ = NULL;
	GtkButton* _tmp50_ = NULL;
	GtkStack* _tmp51_ = NULL;
	GtkStack* _tmp52_ = NULL;
	GtkStack* _tmp53_ = NULL;
	GtkBox* _tmp54_ = NULL;
	GtkStack* _tmp55_ = NULL;
	GtkBox* _tmp56_ = NULL;
	GtkButton* copy_button = NULL;
	GtkButton* _tmp57_ = NULL;
	GtkButton* _tmp58_ = NULL;
	GtkButton* _tmp59_ = NULL;
	GtkButton* _tmp60_ = NULL;
	GtkButton* _tmp61_ = NULL;
	GtkStyleContext* _tmp62_ = NULL;
	GtkImage* copy_ok_image = NULL;
	GtkImage* _tmp63_ = NULL;
	GtkStack* _tmp64_ = NULL;
	GtkStack* _tmp65_ = NULL;
	GtkStack* _tmp66_ = NULL;
	GtkButton* _tmp67_ = NULL;
	GtkStack* _tmp68_ = NULL;
	GtkImage* _tmp69_ = NULL;
	GtkButton* delete_button = NULL;
	GtkButton* _tmp70_ = NULL;
	GtkButton* _tmp71_ = NULL;
	GtkButton* _tmp72_ = NULL;
	GtkButton* _tmp73_ = NULL;
	GtkButton* _tmp74_ = NULL;
	GtkStyleContext* _tmp75_ = NULL;
	GtkBox* title_main_box = NULL;
	GtkBox* _tmp76_ = NULL;
	GtkBox* _tmp77_ = NULL;
	GtkStack* _tmp78_ = NULL;
	GtkBox* _tmp79_ = NULL;
	GtkButton* _tmp80_ = NULL;
	GtkBox* _tmp81_ = NULL;
	GtkStack* _tmp82_ = NULL;
	gchar* display_url = NULL;
	const gchar* _tmp83_ = NULL;
	gchar** _tmp84_ = NULL;
	gchar** _tmp85_ = NULL;
	gchar** _tmp86_ = NULL;
	gint _tmp86__length1 = 0;
	const gchar* _tmp87_ = NULL;
	gchar* _tmp88_ = NULL;
	gchar* _tmp89_ = NULL;
	GtkLabel* url_label = NULL;
	const gchar* _tmp90_ = NULL;
	GtkLabel* _tmp91_ = NULL;
	GtkLabel* _tmp92_ = NULL;
	GtkLabel* _tmp93_ = NULL;
	GtkStyleContext* _tmp94_ = NULL;
	GtkLabel* _tmp95_ = NULL;
	GtkLabel* _tmp96_ = NULL;
	GtkEventBox* url_event_box = NULL;
	GtkEventBox* _tmp97_ = NULL;
	GtkEventBox* _tmp98_ = NULL;
	GtkEventBox* _tmp99_ = NULL;
	GtkLabel* _tmp100_ = NULL;
	GtkEventBox* _tmp101_ = NULL;
	GSettings* _tmp102_ = NULL;
	GSettings* _tmp103_ = NULL;
	gchar* _tmp104_ = NULL;
	gchar* _tmp105_ = NULL;
	const gchar* _tmp106_ = NULL;
	gchar* _tmp111_ = NULL;
	GtkLabel* _tmp112_ = NULL;
	GDateTime* _tmp113_ = NULL;
	gchar* _tmp114_ = NULL;
	gchar* _tmp115_ = NULL;
	GtkStyleContext* _tmp116_ = NULL;
	GSettings* _tmp117_ = NULL;
	GtkBox* url_main_box = NULL;
	GtkBox* _tmp118_ = NULL;
	GtkEventBox* _tmp119_ = NULL;
	GtkButton* _tmp120_ = NULL;
	GtkButton* _tmp121_ = NULL;
	GtkEntry* _tmp122_ = NULL;
	GtkEntry* _tmp123_ = NULL;
	GtkButton* _tmp124_ = NULL;
	GtkButton* _tmp125_ = NULL;
	GtkBox* history_view_item_box = NULL;
	GtkBox* _tmp126_ = NULL;
	GtkBox* _tmp127_ = NULL;
	g_return_val_if_fail (settings != NULL, NULL);
	_data5_ = g_slice_new0 (Block5Data);
	_data5_->_ref_count_ = 1;
	_tmp0_ = settings;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data5_->settings);
	_data5_->settings = _tmp1_;
	self = (HasteAppletHistoryViewItem*) g_object_new (object_type, NULL);
	_data5_->self = g_object_ref (self);
	gtk_widget_set_can_focus ((GtkWidget*) self, FALSE);
	gtk_revealer_set_transition_type ((GtkRevealer*) self, GTK_REVEALER_TRANSITION_TYPE_NONE);
	gtk_revealer_set_transition_duration ((GtkRevealer*) self, (guint) 500);
	_tmp2_ = _data5_->settings;
	_tmp3_ = g_settings_get_value (_tmp2_, "history");
	history_list = _tmp3_;
	_tmp4_ = history_list;
	_tmp5_ = n;
	_tmp6_ = g_variant_get_child_value (_tmp4_, (gsize) _tmp5_);
	history_entry = _tmp6_;
	_tmp7_ = history_entry;
	g_variant_get (_tmp7_, "(xss)", &self->priv->timestamp, &self->priv->title, &self->priv->url, NULL);
	_tmp8_ = self->priv->timestamp;
	_tmp9_ = g_date_time_new_from_unix_local (_tmp8_);
	_data5_->time = _tmp9_;
	_tmp10_ = self->priv->title;
	if (g_strcmp0 (_tmp10_, "") == 0) {
		gchar* _tmp11_ = NULL;
		_tmp11_ = g_strdup ("Untitled");
		_g_free0 (self->priv->title);
		self->priv->title = _tmp11_;
	}
	_tmp12_ = self->priv->title;
	_tmp13_ = string_strip (_tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strdup_printf ("<b>%s</b>", _tmp14_);
	_tmp16_ = _tmp15_;
	_tmp17_ = (GtkLabel*) gtk_label_new (_tmp16_);
	g_object_ref_sink (_tmp17_);
	_g_object_unref0 (self->priv->title_label);
	self->priv->title_label = _tmp17_;
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	_tmp18_ = self->priv->title_label;
	gtk_label_set_use_markup (_tmp18_, TRUE);
	_tmp19_ = self->priv->title_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp19_, GTK_ALIGN_START);
	_tmp20_ = self->priv->title_label;
	gtk_label_set_max_width_chars (_tmp20_, 23);
	_tmp21_ = self->priv->title_label;
	gtk_label_set_ellipsize (_tmp21_, PANGO_ELLIPSIZE_END);
	_tmp22_ = (GtkButton*) gtk_button_new_from_icon_name ("accessories-text-editor-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp22_);
	title_edit_button = _tmp22_;
	_tmp23_ = title_edit_button;
	gtk_button_set_relief (_tmp23_, GTK_RELIEF_NONE);
	_tmp24_ = title_edit_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp24_, FALSE);
	_tmp25_ = title_edit_button;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp25_, "Edit Title");
	_tmp26_ = title_edit_button;
	_tmp27_ = gtk_widget_get_style_context ((GtkWidget*) _tmp26_);
	gtk_style_context_add_class (_tmp27_, "action-button");
	_tmp28_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp28_);
	title_box = _tmp28_;
	_tmp29_ = title_box;
	_tmp30_ = self->priv->title_label;
	gtk_box_pack_start (_tmp29_, (GtkWidget*) _tmp30_, TRUE, TRUE, (guint) 0);
	_tmp31_ = title_box;
	_tmp32_ = title_edit_button;
	gtk_box_pack_end (_tmp31_, (GtkWidget*) _tmp32_, FALSE, FALSE, (guint) 0);
	_tmp33_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp33_);
	_g_object_unref0 (self->priv->title_entry);
	self->priv->title_entry = _tmp33_;
	_tmp34_ = self->priv->title_entry;
	gtk_entry_set_placeholder_text (_tmp34_, "New Title");
	_tmp35_ = self->priv->title_entry;
	gtk_entry_set_max_length (_tmp35_, 50);
	_tmp36_ = self->priv->title_entry;
	gtk_widget_set_margin_end ((GtkWidget*) _tmp36_, 10);
	_tmp37_ = self->priv->title_entry;
	gtk_entry_set_icon_from_icon_name (_tmp37_, GTK_ENTRY_ICON_SECONDARY, "edit-clear-symbolic");
	_tmp38_ = self->priv->title_entry;
	gtk_entry_set_icon_tooltip_text (_tmp38_, GTK_ENTRY_ICON_SECONDARY, "Clear");
	_tmp39_ = self->priv->title_entry;
	g_signal_connect_object (_tmp39_, "icon-press", (GCallback) ___lambda4__gtk_entry_icon_press, self, 0);
	_tmp40_ = (GtkButton*) gtk_button_new_from_icon_name ("emblem-ok-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp40_);
	title_apply_button = _tmp40_;
	_tmp41_ = title_apply_button;
	gtk_button_set_relief (_tmp41_, GTK_RELIEF_NONE);
	_tmp42_ = title_apply_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp42_, FALSE);
	_tmp43_ = title_apply_button;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp43_, "Apply Changes");
	_tmp44_ = title_apply_button;
	_tmp45_ = gtk_widget_get_style_context ((GtkWidget*) _tmp44_);
	gtk_style_context_add_class (_tmp45_, "action-button");
	_tmp46_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp46_);
	title_edit_box = _tmp46_;
	_tmp47_ = title_edit_box;
	_tmp48_ = self->priv->title_entry;
	gtk_box_pack_start (_tmp47_, (GtkWidget*) _tmp48_, TRUE, TRUE, (guint) 0);
	_tmp49_ = title_edit_box;
	_tmp50_ = title_apply_button;
	gtk_box_pack_end (_tmp49_, (GtkWidget*) _tmp50_, FALSE, FALSE, (guint) 0);
	_tmp51_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp51_);
	_data5_->title_stack = _tmp51_;
	_tmp52_ = _data5_->title_stack;
	gtk_stack_set_transition_type (_tmp52_, GTK_STACK_TRANSITION_TYPE_CROSSFADE);
	_tmp53_ = _data5_->title_stack;
	_tmp54_ = title_box;
	gtk_stack_add_named (_tmp53_, (GtkWidget*) _tmp54_, "title_box");
	_tmp55_ = _data5_->title_stack;
	_tmp56_ = title_edit_box;
	gtk_stack_add_named (_tmp55_, (GtkWidget*) _tmp56_, "title_edit_box");
	_tmp57_ = (GtkButton*) gtk_button_new_from_icon_name ("edit-copy-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp57_);
	copy_button = _tmp57_;
	_tmp58_ = copy_button;
	gtk_button_set_relief (_tmp58_, GTK_RELIEF_NONE);
	_tmp59_ = copy_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp59_, FALSE);
	_tmp60_ = copy_button;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp60_, "Copy Haste URL");
	_tmp61_ = copy_button;
	_tmp62_ = gtk_widget_get_style_context ((GtkWidget*) _tmp61_);
	gtk_style_context_add_class (_tmp62_, "action-button");
	_tmp63_ = (GtkImage*) gtk_image_new_from_icon_name ("emblem-ok-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp63_);
	copy_ok_image = _tmp63_;
	_tmp64_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp64_);
	_data5_->copy_stack = _tmp64_;
	_tmp65_ = _data5_->copy_stack;
	gtk_stack_set_transition_type (_tmp65_, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT);
	_tmp66_ = _data5_->copy_stack;
	_tmp67_ = copy_button;
	gtk_stack_add_named (_tmp66_, (GtkWidget*) _tmp67_, "copy_button");
	_tmp68_ = _data5_->copy_stack;
	_tmp69_ = copy_ok_image;
	gtk_stack_add_named (_tmp68_, (GtkWidget*) _tmp69_, "copy_ok_image");
	_tmp70_ = (GtkButton*) gtk_button_new_from_icon_name ("list-remove-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp70_);
	delete_button = _tmp70_;
	_tmp71_ = delete_button;
	gtk_button_set_relief (_tmp71_, GTK_RELIEF_NONE);
	_tmp72_ = delete_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp72_, FALSE);
	_tmp73_ = delete_button;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp73_, "Delete Haste");
	_tmp74_ = delete_button;
	_tmp75_ = gtk_widget_get_style_context ((GtkWidget*) _tmp74_);
	gtk_style_context_add_class (_tmp75_, "action-button");
	_tmp76_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp76_);
	title_main_box = _tmp76_;
	_tmp77_ = title_main_box;
	_tmp78_ = _data5_->title_stack;
	gtk_box_pack_start (_tmp77_, (GtkWidget*) _tmp78_, TRUE, TRUE, (guint) 0);
	_tmp79_ = title_main_box;
	_tmp80_ = delete_button;
	gtk_box_pack_end (_tmp79_, (GtkWidget*) _tmp80_, FALSE, FALSE, (guint) 0);
	_tmp81_ = title_main_box;
	_tmp82_ = _data5_->copy_stack;
	gtk_box_pack_end (_tmp81_, (GtkWidget*) _tmp82_, FALSE, FALSE, (guint) 0);
	_tmp83_ = self->priv->url;
	_tmp85_ = _tmp84_ = g_strsplit (_tmp83_, "://", 0);
	_tmp86_ = _tmp85_;
	_tmp86__length1 = _vala_array_length (_tmp84_);
	_tmp87_ = _tmp86_[1];
	_tmp88_ = g_strdup (_tmp87_);
	_tmp89_ = _tmp88_;
	_tmp86_ = (_vala_array_free (_tmp86_, _tmp86__length1, (GDestroyNotify) g_free), NULL);
	display_url = _tmp89_;
	_tmp90_ = display_url;
	_tmp91_ = (GtkLabel*) gtk_label_new (_tmp90_);
	g_object_ref_sink (_tmp91_);
	url_label = _tmp91_;
	_tmp92_ = url_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp92_, GTK_ALIGN_START);
	_tmp93_ = url_label;
	_tmp94_ = gtk_widget_get_style_context ((GtkWidget*) _tmp93_);
	gtk_style_context_add_class (_tmp94_, "dim-label");
	_tmp95_ = url_label;
	gtk_label_set_max_width_chars (_tmp95_, 23);
	_tmp96_ = url_label;
	gtk_label_set_ellipsize (_tmp96_, PANGO_ELLIPSIZE_MIDDLE);
	_tmp97_ = (GtkEventBox*) gtk_event_box_new ();
	g_object_ref_sink (_tmp97_);
	url_event_box = _tmp97_;
	_tmp98_ = url_event_box;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp98_, "Click to open the link in your browser");
	_tmp99_ = url_event_box;
	_tmp100_ = url_label;
	gtk_container_add ((GtkContainer*) _tmp99_, (GtkWidget*) _tmp100_);
	_tmp101_ = url_event_box;
	g_signal_connect_object ((GtkWidget*) _tmp101_, "button-press-event", (GCallback) ___lambda5__gtk_widget_button_press_event, self, 0);
	_tmp102_ = g_settings_new ("org.gnome.desktop.interface");
	_data5_->gnome_settings = _tmp102_;
	_tmp103_ = _data5_->gnome_settings;
	_tmp104_ = g_settings_get_string (_tmp103_, "clock-format");
	_data5_->time_format = _tmp104_;
	_tmp106_ = _data5_->time_format;
	if (g_strcmp0 (_tmp106_, "24h") == 0) {
		GDateTime* _tmp107_ = NULL;
		gchar* _tmp108_ = NULL;
		_tmp107_ = _data5_->time;
		_tmp108_ = g_date_time_format (_tmp107_, "%H:%M");
		_g_free0 (_tmp105_);
		_tmp105_ = _tmp108_;
	} else {
		GDateTime* _tmp109_ = NULL;
		gchar* _tmp110_ = NULL;
		_tmp109_ = _data5_->time;
		_tmp110_ = g_date_time_format (_tmp109_, "%l:%M %p");
		_g_free0 (_tmp105_);
		_tmp105_ = _tmp110_;
	}
	_tmp111_ = g_strdup (_tmp105_);
	_data5_->time_text = _tmp111_;
	_tmp112_ = (GtkLabel*) gtk_label_new (_data5_->time_text);
	g_object_ref_sink (_tmp112_);
	_data5_->time_label = _tmp112_;
	_tmp113_ = _data5_->time;
	_tmp114_ = g_date_time_format (_tmp113_, "%d %B %Y");
	_tmp115_ = _tmp114_;
	gtk_widget_set_tooltip_text ((GtkWidget*) _data5_->time_label, _tmp115_);
	_g_free0 (_tmp115_);
	gtk_widget_set_valign ((GtkWidget*) _data5_->time_label, GTK_ALIGN_CENTER);
	_tmp116_ = gtk_widget_get_style_context ((GtkWidget*) _data5_->time_label);
	gtk_style_context_add_class (_tmp116_, "dim-label");
	_tmp117_ = _data5_->gnome_settings;
	g_signal_connect_data (_tmp117_, "changed", (GCallback) ___lambda6__g_settings_changed, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp118_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp118_);
	url_main_box = _tmp118_;
	_tmp119_ = url_event_box;
	gtk_box_pack_start (url_main_box, (GtkWidget*) _tmp119_, TRUE, TRUE, (guint) 0);
	gtk_box_pack_end (url_main_box, (GtkWidget*) _data5_->time_label, FALSE, FALSE, (guint) 0);
	_tmp120_ = title_edit_button;
	g_signal_connect_data (_tmp120_, "clicked", (GCallback) ___lambda7__gtk_button_clicked, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp121_ = title_apply_button;
	g_signal_connect_data (_tmp121_, "clicked", (GCallback) ___lambda8__gtk_button_clicked, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp122_ = self->priv->title_entry;
	g_signal_connect_data (_tmp122_, "activate", (GCallback) ___lambda9__gtk_entry_activate, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp123_ = self->priv->title_entry;
	g_signal_connect_data ((GtkWidget*) _tmp123_, "key-press-event", (GCallback) ___lambda10__gtk_widget_key_press_event, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp124_ = copy_button;
	g_signal_connect_data (_tmp124_, "clicked", (GCallback) ___lambda11__gtk_button_clicked, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp125_ = delete_button;
	g_signal_connect_data (_tmp125_, "clicked", (GCallback) ___lambda13__gtk_button_clicked, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
	_tmp126_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp126_);
	history_view_item_box = _tmp126_;
	g_object_set ((GtkWidget*) history_view_item_box, "margin", 5, NULL);
	_tmp127_ = title_main_box;
	gtk_box_pack_start (history_view_item_box, (GtkWidget*) _tmp127_, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start (history_view_item_box, (GtkWidget*) url_main_box, TRUE, TRUE, (guint) 0);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) history_view_item_box);
	gtk_revealer_set_reveal_child ((GtkRevealer*) self, FALSE);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (history_view_item_box);
	_g_object_unref0 (url_main_box);
	_g_free0 (_tmp105_);
	_g_object_unref0 (url_event_box);
	_g_object_unref0 (url_label);
	_g_free0 (display_url);
	_g_object_unref0 (title_main_box);
	_g_object_unref0 (delete_button);
	_g_object_unref0 (copy_ok_image);
	_g_object_unref0 (copy_button);
	_g_object_unref0 (title_edit_box);
	_g_object_unref0 (title_apply_button);
	_g_object_unref0 (title_box);
	_g_object_unref0 (title_edit_button);
	_g_variant_unref0 (history_entry);
	_g_variant_unref0 (history_list);
	block5_data_unref (_data5_);
	_data5_ = NULL;
	return self;
}


HasteAppletHistoryViewItem* haste_applet_history_view_item_new (gint n, GSettings* settings) {
	return haste_applet_history_view_item_construct (HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, n, settings);
}


static gpointer _g_variant_ref0 (gpointer self) {
	return self ? g_variant_ref (self) : NULL;
}


static void _vala_array_add3 (GVariant*** array, int* length, int* size, GVariant* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GVariant*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void __lambda14_ (HasteAppletHistoryViewItem* self) {
	GtkContainer* _tmp0_ = NULL;
	_tmp0_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
	if (_tmp0_ != NULL) {
		GtkContainer* _tmp1_ = NULL;
		_tmp1_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) self);
		gtk_widget_destroy ((GtkWidget*) _tmp1_);
	}
}


static void ___lambda14__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda14_ ((HasteAppletHistoryViewItem*) self);
}


static void haste_applet_history_view_item_delete_item (HasteAppletHistoryViewItem* self, GSettings* settings) {
	GVariant* history_list = NULL;
	GSettings* _tmp0_ = NULL;
	GVariant* _tmp1_ = NULL;
	GVariant** history_l = NULL;
	gint history_l_length1 = 0;
	gint _history_l_size_ = 0;
	GVariant* history_entry_curr = NULL;
	GVariant* _tmp2_ = NULL;
	gsize _tmp3_ = 0UL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (settings != NULL);
	_tmp0_ = settings;
	_tmp1_ = g_settings_get_value (_tmp0_, "history");
	history_list = _tmp1_;
	history_l = NULL;
	history_l_length1 = 0;
	_history_l_size_ = history_l_length1;
	history_entry_curr = NULL;
	_tmp2_ = history_list;
	_tmp3_ = g_variant_n_children (_tmp2_);
	if (_tmp3_ == ((gsize) 1)) {
		GSettings* _tmp4_ = NULL;
		_tmp4_ = settings;
		g_settings_reset (_tmp4_, "history");
	} else {
		GVariant* history_entry_array = NULL;
		GVariant** _tmp19_ = NULL;
		gint _tmp19__length1 = 0;
		GVariant* _tmp20_ = NULL;
		GSettings* _tmp21_ = NULL;
		GVariant* _tmp22_ = NULL;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp5_ = FALSE;
				_tmp5_ = TRUE;
				while (TRUE) {
					gint _tmp7_ = 0;
					GVariant* _tmp8_ = NULL;
					gsize _tmp9_ = 0UL;
					GVariant* _tmp10_ = NULL;
					gint _tmp11_ = 0;
					GVariant* _tmp12_ = NULL;
					gchar* entry_url = NULL;
					GVariant* _tmp13_ = NULL;
					const gchar* _tmp14_ = NULL;
					const gchar* _tmp15_ = NULL;
					if (!_tmp5_) {
						gint _tmp6_ = 0;
						_tmp6_ = i;
						i = _tmp6_ + 1;
					}
					_tmp5_ = FALSE;
					_tmp7_ = i;
					_tmp8_ = history_list;
					_tmp9_ = g_variant_n_children (_tmp8_);
					if (!(((gsize) _tmp7_) < _tmp9_)) {
						break;
					}
					_tmp10_ = history_list;
					_tmp11_ = i;
					_tmp12_ = g_variant_get_child_value (_tmp10_, (gsize) _tmp11_);
					_g_variant_unref0 (history_entry_curr);
					history_entry_curr = _tmp12_;
					entry_url = NULL;
					_tmp13_ = history_entry_curr;
					g_variant_get (_tmp13_, "(xss)", NULL, NULL, &entry_url, NULL);
					_tmp14_ = entry_url;
					_tmp15_ = self->priv->url;
					if (g_strcmp0 (_tmp14_, _tmp15_) != 0) {
						GVariant** _tmp16_ = NULL;
						gint _tmp16__length1 = 0;
						GVariant* _tmp17_ = NULL;
						GVariant* _tmp18_ = NULL;
						_tmp16_ = history_l;
						_tmp16__length1 = history_l_length1;
						_tmp17_ = history_entry_curr;
						_tmp18_ = _g_variant_ref0 (_tmp17_);
						_vala_array_add3 (&history_l, &history_l_length1, &_history_l_size_, _tmp18_);
					}
					_g_free0 (entry_url);
				}
			}
		}
		_tmp19_ = history_l;
		_tmp19__length1 = history_l_length1;
		_tmp20_ = g_variant_new_array (NULL, _tmp19_, _tmp19__length1);
		g_variant_ref_sink (_tmp20_);
		history_entry_array = _tmp20_;
		_tmp21_ = settings;
		_tmp22_ = history_entry_array;
		g_settings_set_value (_tmp21_, "history", _tmp22_);
		_g_variant_unref0 (history_entry_array);
	}
	g_signal_emit_by_name (self, "deletion");
	gtk_revealer_set_transition_type ((GtkRevealer*) self, GTK_REVEALER_TRANSITION_TYPE_SLIDE_DOWN);
	gtk_revealer_set_transition_duration ((GtkRevealer*) self, (guint) 150);
	g_signal_connect_object ((GObject*) self, "notify::child-revealed", (GCallback) ___lambda14__g_object_notify, self, G_CONNECT_AFTER);
	gtk_revealer_set_reveal_child ((GtkRevealer*) self, FALSE);
	_g_variant_unref0 (history_entry_curr);
	history_l = (_vala_array_free (history_l, history_l_length1, (GDestroyNotify) g_variant_unref), NULL);
	_g_variant_unref0 (history_list);
}


static void _vala_array_add4 (GVariant*** array, int* length, int* size, GVariant* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GVariant*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _vala_array_add5 (GVariant*** array, int* length, int* size, GVariant* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GVariant*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void haste_applet_history_view_item_apply_changes (HasteAppletHistoryViewItem* self, GSettings* settings) {
	gchar* _tmp0_ = NULL;
	GtkEntry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	GtkLabel* _tmp14_ = NULL;
	GVariant* history_list = NULL;
	GSettings* _tmp15_ = NULL;
	GVariant* _tmp16_ = NULL;
	GVariant** history_variant_list = NULL;
	gint history_variant_list_length1 = 0;
	gint _history_variant_list_size_ = 0;
	GVariant* history_entry_curr = NULL;
	GVariant* history_entry_new = NULL;
	GVariant* history_entry_array = NULL;
	GVariant** _tmp49_ = NULL;
	gint _tmp49__length1 = 0;
	GVariant* _tmp50_ = NULL;
	GSettings* _tmp51_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (settings != NULL);
	_tmp1_ = self->priv->title_entry;
	_tmp2_ = gtk_entry_get_text (_tmp1_);
	_tmp3_ = _tmp2_;
	if (g_strcmp0 (_tmp3_, "") == 0) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = g_strdup ("Untitled");
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp4_;
	} else {
		GtkEntry* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		_tmp5_ = self->priv->title_entry;
		_tmp6_ = gtk_entry_get_text (_tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = string_strip (_tmp7_);
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp8_;
	}
	_tmp9_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->title);
	self->priv->title = _tmp9_;
	_tmp10_ = self->priv->title_label;
	_tmp11_ = self->priv->title;
	_tmp12_ = g_strdup_printf ("<b>%s</b>", _tmp11_);
	_tmp13_ = _tmp12_;
	gtk_label_set_text (_tmp10_, _tmp13_);
	_g_free0 (_tmp13_);
	_tmp14_ = self->priv->title_label;
	gtk_label_set_use_markup (_tmp14_, TRUE);
	_tmp15_ = settings;
	_tmp16_ = g_settings_get_value (_tmp15_, "history");
	history_list = _tmp16_;
	history_variant_list = NULL;
	history_variant_list_length1 = 0;
	_history_variant_list_size_ = history_variant_list_length1;
	history_entry_curr = NULL;
	history_entry_new = NULL;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp17_ = FALSE;
			_tmp17_ = TRUE;
			while (TRUE) {
				gint _tmp19_ = 0;
				GVariant* _tmp20_ = NULL;
				gsize _tmp21_ = 0UL;
				GVariant* _tmp22_ = NULL;
				gint _tmp23_ = 0;
				GVariant* _tmp24_ = NULL;
				gchar* entry_url = NULL;
				GVariant* _tmp25_ = NULL;
				const gchar* _tmp26_ = NULL;
				const gchar* _tmp27_ = NULL;
				if (!_tmp17_) {
					gint _tmp18_ = 0;
					_tmp18_ = i;
					i = _tmp18_ + 1;
				}
				_tmp17_ = FALSE;
				_tmp19_ = i;
				_tmp20_ = history_list;
				_tmp21_ = g_variant_n_children (_tmp20_);
				if (!(((gsize) _tmp19_) < _tmp21_)) {
					break;
				}
				_tmp22_ = history_list;
				_tmp23_ = i;
				_tmp24_ = g_variant_get_child_value (_tmp22_, (gsize) _tmp23_);
				_g_variant_unref0 (history_entry_curr);
				history_entry_curr = _tmp24_;
				entry_url = NULL;
				_tmp25_ = history_entry_curr;
				g_variant_get (_tmp25_, "(xss)", NULL, NULL, &entry_url, NULL);
				_tmp26_ = entry_url;
				_tmp27_ = self->priv->url;
				if (g_strcmp0 (_tmp26_, _tmp27_) == 0) {
					GVariant* entry_timestamp_variant = NULL;
					gint64 _tmp28_ = 0LL;
					GVariant* _tmp29_ = NULL;
					GVariant* entry_title_variant = NULL;
					const gchar* _tmp30_ = NULL;
					GVariant* _tmp31_ = NULL;
					GVariant* entry_url_variant = NULL;
					const gchar* _tmp32_ = NULL;
					GVariant* _tmp33_ = NULL;
					GVariant* _tmp34_ = NULL;
					GVariant* _tmp35_ = NULL;
					GVariant* _tmp36_ = NULL;
					GVariant* _tmp37_ = NULL;
					GVariant* _tmp38_ = NULL;
					GVariant* _tmp39_ = NULL;
					GVariant** _tmp40_ = NULL;
					GVariant** _tmp41_ = NULL;
					gint _tmp41__length1 = 0;
					GVariant* _tmp42_ = NULL;
					GVariant** _tmp43_ = NULL;
					gint _tmp43__length1 = 0;
					GVariant* _tmp44_ = NULL;
					GVariant* _tmp45_ = NULL;
					_tmp28_ = self->priv->timestamp;
					_tmp29_ = g_variant_new_int64 (_tmp28_);
					g_variant_ref_sink (_tmp29_);
					entry_timestamp_variant = _tmp29_;
					_tmp30_ = self->priv->title;
					_tmp31_ = g_variant_new_string (_tmp30_);
					g_variant_ref_sink (_tmp31_);
					entry_title_variant = _tmp31_;
					_tmp32_ = self->priv->url;
					_tmp33_ = g_variant_new_string (_tmp32_);
					g_variant_ref_sink (_tmp33_);
					entry_url_variant = _tmp33_;
					_tmp34_ = entry_timestamp_variant;
					_tmp35_ = _g_variant_ref0 (_tmp34_);
					_tmp36_ = entry_title_variant;
					_tmp37_ = _g_variant_ref0 (_tmp36_);
					_tmp38_ = entry_url_variant;
					_tmp39_ = _g_variant_ref0 (_tmp38_);
					_tmp40_ = g_new0 (GVariant*, 3 + 1);
					_tmp40_[0] = _tmp35_;
					_tmp40_[1] = _tmp37_;
					_tmp40_[2] = _tmp39_;
					_tmp41_ = _tmp40_;
					_tmp41__length1 = 3;
					_tmp42_ = g_variant_new_tuple (_tmp41_, 3);
					g_variant_ref_sink (_tmp42_);
					_g_variant_unref0 (history_entry_new);
					history_entry_new = _tmp42_;
					_tmp41_ = (_vala_array_free (_tmp41_, _tmp41__length1, (GDestroyNotify) g_variant_unref), NULL);
					_tmp43_ = history_variant_list;
					_tmp43__length1 = history_variant_list_length1;
					_tmp44_ = history_entry_new;
					_tmp45_ = _g_variant_ref0 (_tmp44_);
					_vala_array_add4 (&history_variant_list, &history_variant_list_length1, &_history_variant_list_size_, _tmp45_);
					_g_variant_unref0 (entry_url_variant);
					_g_variant_unref0 (entry_title_variant);
					_g_variant_unref0 (entry_timestamp_variant);
				} else {
					GVariant** _tmp46_ = NULL;
					gint _tmp46__length1 = 0;
					GVariant* _tmp47_ = NULL;
					GVariant* _tmp48_ = NULL;
					_tmp46_ = history_variant_list;
					_tmp46__length1 = history_variant_list_length1;
					_tmp47_ = history_entry_curr;
					_tmp48_ = _g_variant_ref0 (_tmp47_);
					_vala_array_add5 (&history_variant_list, &history_variant_list_length1, &_history_variant_list_size_, _tmp48_);
				}
				_g_free0 (entry_url);
			}
		}
	}
	_tmp49_ = history_variant_list;
	_tmp49__length1 = history_variant_list_length1;
	_tmp50_ = g_variant_new_array (NULL, _tmp49_, _tmp49__length1);
	g_variant_ref_sink (_tmp50_);
	history_entry_array = _tmp50_;
	_tmp51_ = settings;
	g_settings_set_value (_tmp51_, "history", history_entry_array);
	_g_variant_unref0 (history_entry_array);
	_g_variant_unref0 (history_entry_new);
	_g_variant_unref0 (history_entry_curr);
	history_variant_list = (_vala_array_free (history_variant_list, history_variant_list_length1, (GDestroyNotify) g_variant_unref), NULL);
	_g_variant_unref0 (history_list);
	_g_free0 (_tmp0_);
}


static void haste_applet_history_view_item_class_init (HasteAppletHistoryViewItemClass * klass) {
	haste_applet_history_view_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HasteAppletHistoryViewItemPrivate));
	G_OBJECT_CLASS (klass)->finalize = haste_applet_history_view_item_finalize;
	g_signal_new ("copy", HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	g_signal_new ("deletion", HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void haste_applet_history_view_item_instance_init (HasteAppletHistoryViewItem * self) {
	self->priv = HASTE_APPLET_HISTORY_VIEW_ITEM_GET_PRIVATE (self);
}


static void haste_applet_history_view_item_finalize (GObject* obj) {
	HasteAppletHistoryViewItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HASTE_APPLET_TYPE_HISTORY_VIEW_ITEM, HasteAppletHistoryViewItem);
	_g_object_unref0 (self->priv->title_label);
	_g_object_unref0 (self->priv->title_entry);
	_g_free0 (self->priv->title);
	_g_free0 (self->priv->url);
	G_OBJECT_CLASS (haste_applet_history_view_item_parent_class)->finalize (obj);
}


GType haste_applet_history_view_item_get_type (void) {
	return haste_applet_history_view_item_type_id;
}


GType haste_applet_history_view_item_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (HasteAppletHistoryViewItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) haste_applet_history_view_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HasteAppletHistoryViewItem), 0, (GInstanceInitFunc) haste_applet_history_view_item_instance_init, NULL };
	haste_applet_history_view_item_type_id = g_type_module_register_type (module, gtk_revealer_get_type (), "HasteAppletHistoryViewItem", &g_define_type_info, 0);
	return haste_applet_history_view_item_type_id;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



