/* NewHasteView.c generated by valac 0.32.1, the Vala compiler
 * generated from NewHasteView.vala, do not modify */

/*
 * This file is part of haste-applet
 *
 * Copyright (C) 2016 Stefan Ric <stfric369@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>
#include <gdk/gdk.h>
#include <stdio.h>


#define HASTE_APPLET_TYPE_NEW_HASTE_VIEW (haste_applet_new_haste_view_get_type ())
#define HASTE_APPLET_NEW_HASTE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteView))
#define HASTE_APPLET_NEW_HASTE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteViewClass))
#define HASTE_APPLET_IS_NEW_HASTE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_NEW_HASTE_VIEW))
#define HASTE_APPLET_IS_NEW_HASTE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_NEW_HASTE_VIEW))
#define HASTE_APPLET_NEW_HASTE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteViewClass))

typedef struct _HasteAppletNewHasteView HasteAppletNewHasteView;
typedef struct _HasteAppletNewHasteViewClass HasteAppletNewHasteViewClass;
typedef struct _HasteAppletNewHasteViewPrivate HasteAppletNewHasteViewPrivate;

#define HASTE_APPLET_TYPE_HISTORY_VIEW (haste_applet_history_view_get_type ())
#define HASTE_APPLET_HISTORY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW, HasteAppletHistoryView))
#define HASTE_APPLET_HISTORY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), HASTE_APPLET_TYPE_HISTORY_VIEW, HasteAppletHistoryViewClass))
#define HASTE_APPLET_IS_HISTORY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW))
#define HASTE_APPLET_IS_HISTORY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), HASTE_APPLET_TYPE_HISTORY_VIEW))
#define HASTE_APPLET_HISTORY_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), HASTE_APPLET_TYPE_HISTORY_VIEW, HasteAppletHistoryViewClass))

typedef struct _HasteAppletHistoryView HasteAppletHistoryView;
typedef struct _HasteAppletHistoryViewClass HasteAppletHistoryViewClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))
typedef struct _Block2Data Block2Data;
typedef struct _Block3Data Block3Data;

struct _HasteAppletNewHasteView {
	GtkGrid parent_instance;
	HasteAppletNewHasteViewPrivate * priv;
	GtkEntry* title_entry;
	GtkTextView* textview;
	GtkButton* post_button;
	HasteAppletHistoryView* history_view;
};

struct _HasteAppletNewHasteViewClass {
	GtkGridClass parent_class;
};

struct _HasteAppletNewHasteViewPrivate {
	GtkTextBuffer* textbuffer;
	GtkTextIter* start_iter;
	GtkTextIter* end_iter;
	GtkRevealer* error_message_revealer;
	GtkLabel* error_message_label;
	gchar* text;
	gchar* _haste_address;
	gchar* _protocol;
	gboolean _is_editing;
	gboolean _haste_address_invalid;
};

struct _Block2Data {
	int _ref_count_;
	HasteAppletNewHasteView* self;
	SoupSession* session;
	GtkStack* stack;
};

struct _Block3Data {
	int _ref_count_;
	HasteAppletNewHasteView* self;
	GtkStack* stack;
};


static gpointer haste_applet_new_haste_view_parent_class = NULL;
static GType haste_applet_new_haste_view_type_id = 0;

GType haste_applet_new_haste_view_get_type (void) G_GNUC_CONST;
GType haste_applet_new_haste_view_register_type (GTypeModule * module);
GType haste_applet_history_view_get_type (void) G_GNUC_CONST;
GType haste_applet_history_view_register_type (GTypeModule * module);
#define HASTE_APPLET_NEW_HASTE_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteViewPrivate))
enum  {
	HASTE_APPLET_NEW_HASTE_VIEW_DUMMY_PROPERTY,
	HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS,
	HASTE_APPLET_NEW_HASTE_VIEW_PROTOCOL,
	HASTE_APPLET_NEW_HASTE_VIEW_IS_EDITING,
	HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS_INVALID
};
HasteAppletNewHasteView* haste_applet_new_haste_view_new (GtkStack* stack);
HasteAppletNewHasteView* haste_applet_new_haste_view_construct (GType object_type, GtkStack* stack);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda18_ (Block2Data* _data2_);
static void ___lambda18__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda19_ (HasteAppletNewHasteView* self);
static void ___lambda19__gtk_entry_icon_press (GtkEntry* _sender, GtkEntryIconPosition p0, GdkEvent* p1, gpointer self);
static void __lambda20_ (HasteAppletNewHasteView* self);
static GtkTextIter* _gtk_text_iter_dup (GtkTextIter* self);
void haste_applet_new_haste_view_set_is_editing (HasteAppletNewHasteView* self, gboolean value);
gboolean haste_applet_new_haste_view_get_haste_address_invalid (HasteAppletNewHasteView* self);
static void ___lambda20__gtk_text_buffer_changed (GtkTextBuffer* _sender, gpointer self);
static void __lambda21_ (HasteAppletNewHasteView* self);
static void ___lambda21__gtk_editable_changed (GtkEditable* _sender, gpointer self);
static void __lambda22_ (Block2Data* _data2_);
static void haste_applet_new_haste_view_upload_haste (HasteAppletNewHasteView* self, SoupSession* session, GtkStack* stack);
static void ___lambda22__gtk_button_clicked (GtkButton* _sender, gpointer self);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
void haste_applet_new_haste_view_dismiss_error_message (HasteAppletNewHasteView* self);
const gchar* haste_applet_new_haste_view_get_haste_address (HasteAppletNewHasteView* self);
void haste_applet_new_haste_view_set_haste_address (HasteAppletNewHasteView* self, const gchar* value);
const gchar* haste_applet_new_haste_view_get_protocol (HasteAppletNewHasteView* self);
static void __lambda23_ (Block3Data* _data3_, SoupSession* sess, SoupMessage* mess);
void haste_applet_new_haste_view_show_error_message (HasteAppletNewHasteView* self, const gchar* message);
void haste_applet_history_view_add_to_history (HasteAppletHistoryView* self, const gchar* link, const gchar* title);
static void ___lambda23__soup_session_callback (SoupSession* session, SoupMessage* msg, gpointer self);
void haste_applet_new_haste_view_set_protocol (HasteAppletNewHasteView* self, const gchar* value);
gboolean haste_applet_new_haste_view_get_is_editing (HasteAppletNewHasteView* self);
void haste_applet_new_haste_view_set_haste_address_invalid (HasteAppletNewHasteView* self, gboolean value);
static void haste_applet_new_haste_view_finalize (GObject* obj);
static void _vala_haste_applet_new_haste_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_haste_applet_new_haste_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		HasteAppletNewHasteView* self;
		self = _data2_->self;
		_g_object_unref0 (_data2_->session);
		_g_object_unref0 (_data2_->stack);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}


static void __lambda18_ (Block2Data* _data2_) {
	HasteAppletNewHasteView* self;
	GtkStack* _tmp0_ = NULL;
	self = _data2_->self;
	_tmp0_ = _data2_->stack;
	gtk_stack_set_visible_child_name (_tmp0_, "history_view");
}


static void ___lambda18__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda18_ (self);
}


static void __lambda19_ (HasteAppletNewHasteView* self) {
	GtkEntry* _tmp0_ = NULL;
	_tmp0_ = self->title_entry;
	gtk_entry_set_text (_tmp0_, "");
}


static void ___lambda19__gtk_entry_icon_press (GtkEntry* _sender, GtkEntryIconPosition p0, GdkEvent* p1, gpointer self) {
	__lambda19_ ((HasteAppletNewHasteView*) self);
}


static GtkTextIter* _gtk_text_iter_dup (GtkTextIter* self) {
	GtkTextIter* dup;
	dup = g_new0 (GtkTextIter, 1);
	memcpy (dup, self, sizeof (GtkTextIter));
	return dup;
}


static gpointer __gtk_text_iter_dup0 (gpointer self) {
	return self ? _gtk_text_iter_dup (self) : NULL;
}


static void __lambda20_ (HasteAppletNewHasteView* self) {
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextIter _tmp1_ = {0};
	GtkTextIter _tmp2_ = {0};
	GtkTextIter _tmp3_ = {0};
	GtkTextIter* _tmp4_ = NULL;
	GtkTextIter _tmp5_ = {0};
	GtkTextIter* _tmp6_ = NULL;
	GtkTextBuffer* _tmp7_ = NULL;
	GtkTextIter* _tmp8_ = NULL;
	GtkTextIter* _tmp9_ = NULL;
	GtkTextIter _tmp10_ = {0};
	GtkTextIter _tmp11_ = {0};
	gchar* _tmp12_ = NULL;
	const gchar* _tmp13_ = NULL;
	_tmp0_ = self->priv->textbuffer;
	gtk_text_buffer_get_bounds (_tmp0_, &_tmp1_, &_tmp2_);
	_g_free0 (self->priv->start_iter);
	_tmp3_ = _tmp1_;
	_tmp4_ = __gtk_text_iter_dup0 (&_tmp3_);
	self->priv->start_iter = _tmp4_;
	_g_free0 (self->priv->end_iter);
	_tmp5_ = _tmp2_;
	_tmp6_ = __gtk_text_iter_dup0 (&_tmp5_);
	self->priv->end_iter = _tmp6_;
	_tmp7_ = self->priv->textbuffer;
	_tmp8_ = self->priv->start_iter;
	_tmp9_ = self->priv->end_iter;
	_tmp10_ = *_tmp8_;
	_tmp11_ = *_tmp9_;
	_tmp12_ = gtk_text_buffer_get_text (_tmp7_, &_tmp10_, &_tmp11_, TRUE);
	_g_free0 (self->priv->text);
	self->priv->text = _tmp12_;
	_tmp13_ = self->priv->text;
	if (g_strcmp0 (_tmp13_, "") == 0) {
		GtkButton* _tmp14_ = NULL;
		GtkEntry* _tmp15_ = NULL;
		const gchar* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
		_tmp14_ = self->post_button;
		gtk_widget_set_sensitive ((GtkWidget*) _tmp14_, FALSE);
		_tmp15_ = self->title_entry;
		_tmp16_ = gtk_entry_get_text (_tmp15_);
		_tmp17_ = _tmp16_;
		if (g_strcmp0 (_tmp17_, "") == 0) {
			haste_applet_new_haste_view_set_is_editing (self, FALSE);
		}
	} else {
		gboolean _tmp18_ = FALSE;
		_tmp18_ = self->priv->_haste_address_invalid;
		if (!_tmp18_) {
			GtkButton* _tmp19_ = NULL;
			_tmp19_ = self->post_button;
			gtk_widget_set_sensitive ((GtkWidget*) _tmp19_, TRUE);
		}
		haste_applet_new_haste_view_set_is_editing (self, TRUE);
	}
}


static void ___lambda20__gtk_text_buffer_changed (GtkTextBuffer* _sender, gpointer self) {
	__lambda20_ ((HasteAppletNewHasteView*) self);
}


static void __lambda21_ (HasteAppletNewHasteView* self) {
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	_tmp0_ = self->title_entry;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = _tmp1_;
	if (g_strcmp0 (_tmp2_, "") == 0) {
		const gchar* _tmp3_ = NULL;
		_tmp3_ = self->priv->text;
		if (g_strcmp0 (_tmp3_, "") == 0) {
			haste_applet_new_haste_view_set_is_editing (self, FALSE);
		}
	} else {
		haste_applet_new_haste_view_set_is_editing (self, TRUE);
	}
}


static void ___lambda21__gtk_editable_changed (GtkEditable* _sender, gpointer self) {
	__lambda21_ ((HasteAppletNewHasteView*) self);
}


static void __lambda22_ (Block2Data* _data2_) {
	HasteAppletNewHasteView* self;
	GtkStack* _tmp0_ = NULL;
	self = _data2_->self;
	_tmp0_ = _data2_->stack;
	haste_applet_new_haste_view_upload_haste (self, _data2_->session, _tmp0_);
}


static void ___lambda22__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda22_ (self);
}


HasteAppletNewHasteView* haste_applet_new_haste_view_construct (GType object_type, GtkStack* stack) {
	HasteAppletNewHasteView * self = NULL;
	Block2Data* _data2_;
	GtkStack* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkButton* header_back_button = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
	GtkEntry* _tmp4_ = NULL;
	GtkEntry* _tmp5_ = NULL;
	GtkEntry* _tmp6_ = NULL;
	GtkEntry* _tmp7_ = NULL;
	GtkEntry* _tmp8_ = NULL;
	GtkBox* header_box = NULL;
	GtkBox* _tmp9_ = NULL;
	GtkEntry* _tmp10_ = NULL;
	GtkTextView* _tmp11_ = NULL;
	GtkTextView* _tmp12_ = NULL;
	GtkTextView* _tmp13_ = NULL;
	GtkTextView* _tmp14_ = NULL;
	GtkTextView* _tmp15_ = NULL;
	GtkTextView* _tmp16_ = NULL;
	GtkTextView* _tmp17_ = NULL;
	GtkScrolledWindow* scroller = NULL;
	GtkScrolledWindow* _tmp18_ = NULL;
	GtkTextView* _tmp19_ = NULL;
	GtkButton* _tmp20_ = NULL;
	GtkButton* _tmp21_ = NULL;
	GtkButton* _tmp22_ = NULL;
	GtkButton* _tmp23_ = NULL;
	GtkWidget* _tmp24_ = NULL;
	GtkTextView* _tmp25_ = NULL;
	GtkTextBuffer* _tmp26_ = NULL;
	GtkTextBuffer* _tmp27_ = NULL;
	GtkTextBuffer* _tmp28_ = NULL;
	GtkEntry* _tmp29_ = NULL;
	SoupSession* _tmp30_ = NULL;
	GtkButton* _tmp31_ = NULL;
	GtkLabel* _tmp32_ = NULL;
	GtkLabel* _tmp33_ = NULL;
	GtkStyleContext* _tmp34_ = NULL;
	GtkRevealer* _tmp35_ = NULL;
	GtkRevealer* _tmp36_ = NULL;
	GtkRevealer* _tmp37_ = NULL;
	GtkRevealer* _tmp38_ = NULL;
	GtkLabel* _tmp39_ = NULL;
	GtkButton* _tmp40_ = NULL;
	GtkRevealer* _tmp41_ = NULL;
	g_return_val_if_fail (stack != NULL, NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_tmp0_ = stack;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data2_->stack);
	_data2_->stack = _tmp1_;
	self = (HasteAppletNewHasteView*) g_object_new (object_type, "row-spacing", 5, "border-width", 5, NULL);
	_data2_->self = g_object_ref (self);
	_tmp2_ = (GtkButton*) gtk_button_new_from_icon_name ("go-previous-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp2_);
	header_back_button = _tmp2_;
	gtk_widget_set_can_focus ((GtkWidget*) header_back_button, FALSE);
	gtk_widget_set_tooltip_text ((GtkWidget*) header_back_button, "Back");
	g_signal_connect_data (header_back_button, "clicked", (GCallback) ___lambda18__gtk_button_clicked, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	_tmp3_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->title_entry);
	self->title_entry = _tmp3_;
	_tmp4_ = self->title_entry;
	gtk_entry_set_placeholder_text (_tmp4_, "Title (Optional)");
	_tmp5_ = self->title_entry;
	gtk_entry_set_max_length (_tmp5_, 50);
	_tmp6_ = self->title_entry;
	gtk_entry_set_icon_from_icon_name (_tmp6_, GTK_ENTRY_ICON_SECONDARY, "edit-clear-symbolic");
	_tmp7_ = self->title_entry;
	gtk_entry_set_icon_tooltip_text (_tmp7_, GTK_ENTRY_ICON_SECONDARY, "Clear");
	_tmp8_ = self->title_entry;
	g_signal_connect_object (_tmp8_, "icon-press", (GCallback) ___lambda19__gtk_entry_icon_press, self, 0);
	_tmp9_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 5);
	g_object_ref_sink (_tmp9_);
	header_box = _tmp9_;
	gtk_box_pack_start (header_box, (GtkWidget*) header_back_button, FALSE, FALSE, (guint) 0);
	_tmp10_ = self->title_entry;
	gtk_box_pack_start (header_box, (GtkWidget*) _tmp10_, TRUE, TRUE, (guint) 0);
	_tmp11_ = (GtkTextView*) gtk_text_view_new ();
	g_object_ref_sink (_tmp11_);
	_g_object_unref0 (self->textview);
	self->textview = _tmp11_;
	_tmp12_ = self->textview;
	_tmp13_ = self->textview;
	gtk_text_view_set_bottom_margin (_tmp13_, 10);
	gtk_text_view_set_top_margin (_tmp12_, 10);
	_tmp14_ = self->textview;
	_tmp15_ = self->textview;
	gtk_text_view_set_right_margin (_tmp15_, 10);
	gtk_text_view_set_left_margin (_tmp14_, 10);
	_tmp16_ = self->textview;
	_tmp17_ = self->textview;
	gtk_text_view_set_monospace (_tmp17_, TRUE);
	gtk_text_view_set_editable (_tmp16_, TRUE);
	_tmp18_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp18_);
	scroller = _tmp18_;
	gtk_scrolled_window_set_shadow_type (scroller, GTK_SHADOW_IN);
	gtk_widget_set_size_request ((GtkWidget*) scroller, 330, 330);
	_tmp19_ = self->textview;
	gtk_container_add ((GtkContainer*) scroller, (GtkWidget*) _tmp19_);
	_tmp20_ = (GtkButton*) gtk_button_new_with_label ("Haste it!");
	g_object_ref_sink (_tmp20_);
	_g_object_unref0 (self->post_button);
	self->post_button = _tmp20_;
	_tmp21_ = self->post_button;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp21_, FALSE);
	_tmp22_ = self->post_button;
	gtk_widget_set_can_focus ((GtkWidget*) _tmp22_, FALSE);
	_tmp23_ = self->post_button;
	_tmp24_ = gtk_bin_get_child ((GtkBin*) _tmp23_);
	g_object_set (_tmp24_, "margin", 5, NULL);
	_tmp25_ = self->textview;
	_tmp26_ = gtk_text_view_get_buffer (_tmp25_);
	_tmp27_ = _g_object_ref0 (_tmp26_);
	_g_object_unref0 (self->priv->textbuffer);
	self->priv->textbuffer = _tmp27_;
	_tmp28_ = self->priv->textbuffer;
	g_signal_connect_object (_tmp28_, "changed", (GCallback) ___lambda20__gtk_text_buffer_changed, self, 0);
	_tmp29_ = self->title_entry;
	g_signal_connect_object ((GtkEditable*) _tmp29_, "changed", (GCallback) ___lambda21__gtk_editable_changed, self, 0);
	_tmp30_ = soup_session_new ();
	_data2_->session = _tmp30_;
	g_object_set (_data2_->session, "ssl-strict", FALSE, NULL);
	_tmp31_ = self->post_button;
	g_signal_connect_data (_tmp31_, "clicked", (GCallback) ___lambda22__gtk_button_clicked, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	_tmp32_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp32_);
	_g_object_unref0 (self->priv->error_message_label);
	self->priv->error_message_label = _tmp32_;
	_tmp33_ = self->priv->error_message_label;
	_tmp34_ = gtk_widget_get_style_context ((GtkWidget*) _tmp33_);
	gtk_style_context_add_class (_tmp34_, "dim-label");
	_tmp35_ = (GtkRevealer*) gtk_revealer_new ();
	g_object_ref_sink (_tmp35_);
	_g_object_unref0 (self->priv->error_message_revealer);
	self->priv->error_message_revealer = _tmp35_;
	_tmp36_ = self->priv->error_message_revealer;
	gtk_widget_set_no_show_all ((GtkWidget*) _tmp36_, TRUE);
	_tmp37_ = self->priv->error_message_revealer;
	gtk_widget_hide ((GtkWidget*) _tmp37_);
	_tmp38_ = self->priv->error_message_revealer;
	_tmp39_ = self->priv->error_message_label;
	gtk_container_add ((GtkContainer*) _tmp38_, (GtkWidget*) _tmp39_);
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) header_box, 0, 0, 1, 1);
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) scroller, 0, 1, 1, 1);
	_tmp40_ = self->post_button;
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp40_, 0, 2, 1, 1);
	_tmp41_ = self->priv->error_message_revealer;
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp41_, 0, 3, 1, 1);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (scroller);
	_g_object_unref0 (header_box);
	_g_object_unref0 (header_back_button);
	block2_data_unref (_data2_);
	_data2_ = NULL;
	return self;
}


HasteAppletNewHasteView* haste_applet_new_haste_view_new (GtkStack* stack) {
	return haste_applet_new_haste_view_construct (HASTE_APPLET_TYPE_NEW_HASTE_VIEW, stack);
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		HasteAppletNewHasteView* self;
		self = _data3_->self;
		_g_object_unref0 (_data3_->stack);
		_g_object_unref0 (self);
		g_slice_free (Block3Data, _data3_);
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	g_return_val_if_fail (_tmp8_, NULL);
	_tmp13_ = end;
	if (_tmp13_ >= ((glong) 0)) {
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
		_tmp14_ = end;
		_tmp15_ = string_length;
		_tmp12_ = _tmp14_ <= _tmp15_;
	} else {
		_tmp12_ = FALSE;
	}
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp16_ = start;
	_tmp17_ = end;
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	_tmp20_ = start;
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
	result = _tmp21_;
	return result;
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


static void __lambda23_ (Block3Data* _data3_, SoupSession* sess, SoupMessage* mess) {
	HasteAppletNewHasteView* self;
	gchar* link = NULL;
	gchar* _tmp0_ = NULL;
	gchar* title = NULL;
	GtkEntry* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	FILE* _tmp24_ = NULL;
	SoupMessage* _tmp25_ = NULL;
	SoupMessageBody* _tmp26_ = NULL;
	guint8* _tmp27_ = NULL;
	gint _tmp27__length1 = 0;
	FILE* _tmp28_ = NULL;
	SoupMessage* _tmp29_ = NULL;
	guint _tmp30_ = 0U;
	guint _tmp31_ = 0U;
	gboolean _tmp32_ = FALSE;
	const gchar* _tmp33_ = NULL;
	GtkButton* _tmp49_ = NULL;
	GtkEntry* _tmp50_ = NULL;
	GtkTextView* _tmp51_ = NULL;
	GtkButton* _tmp52_ = NULL;
	GtkButton* _tmp53_ = NULL;
	GtkWidget* _tmp54_ = NULL;
	self = _data3_->self;
	g_return_if_fail (sess != NULL);
	g_return_if_fail (mess != NULL);
	_tmp0_ = g_strdup ("");
	link = _tmp0_;
	{
		gint i = 0;
		i = 8;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_ = 0;
				SoupMessage* _tmp4_ = NULL;
				SoupMessageBody* _tmp5_ = NULL;
				guint8* _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				const gchar* _tmp7_ = NULL;
				SoupMessage* _tmp8_ = NULL;
				SoupMessageBody* _tmp9_ = NULL;
				guint8* _tmp10_ = NULL;
				gint _tmp10__length1 = 0;
				gint _tmp11_ = 0;
				guint8 _tmp12_ = 0U;
				gchar* _tmp13_ = NULL;
				gchar* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = mess;
				_tmp5_ = _tmp4_->response_body;
				_tmp6_ = _tmp5_->data;
				_tmp6__length1 = (gint) _tmp5_->length;
				if (!(_tmp3_ < (_tmp6__length1 - 2))) {
					break;
				}
				_tmp7_ = link;
				_tmp8_ = mess;
				_tmp9_ = _tmp8_->response_body;
				_tmp10_ = _tmp9_->data;
				_tmp10__length1 = (gint) _tmp9_->length;
				_tmp11_ = i;
				_tmp12_ = _tmp10_[_tmp11_];
				_tmp13_ = g_strdup_printf ("%c", (gchar) _tmp12_);
				_tmp14_ = _tmp13_;
				_tmp15_ = g_strconcat (_tmp7_, _tmp14_, NULL);
				_g_free0 (link);
				link = _tmp15_;
				_g_free0 (_tmp14_);
			}
		}
	}
	title = NULL;
	_tmp16_ = self->title_entry;
	_tmp17_ = gtk_entry_get_text (_tmp16_);
	_tmp18_ = _tmp17_;
	if (g_strcmp0 (_tmp18_, "") == 0) {
		gchar* _tmp19_ = NULL;
		_tmp19_ = g_strdup ("Untitled");
		_g_free0 (title);
		title = _tmp19_;
	} else {
		GtkEntry* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		const gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		_tmp20_ = self->title_entry;
		_tmp21_ = gtk_entry_get_text (_tmp20_);
		_tmp22_ = _tmp21_;
		_tmp23_ = g_strdup (_tmp22_);
		_g_free0 (title);
		title = _tmp23_;
	}
	_tmp24_ = stdout;
	_tmp25_ = mess;
	_tmp26_ = _tmp25_->response_body;
	_tmp27_ = _tmp26_->data;
	_tmp27__length1 = (gint) _tmp26_->length;
	fprintf (_tmp24_, "Data: \n%s\n", (const gchar*) _tmp27_);
	_tmp28_ = stdout;
	_tmp29_ = mess;
	g_object_get (_tmp29_, "status-code", &_tmp30_, NULL);
	_tmp31_ = _tmp30_;
	fprintf (_tmp28_, "Status Code: %u\n", _tmp31_);
	_tmp33_ = link;
	if (g_strcmp0 (_tmp33_, "") == 0) {
		_tmp32_ = TRUE;
	} else {
		const gchar* _tmp34_ = NULL;
		gint _tmp35_ = 0;
		gint _tmp36_ = 0;
		_tmp34_ = link;
		_tmp35_ = strlen (_tmp34_);
		_tmp36_ = _tmp35_;
		_tmp32_ = _tmp36_ > 30;
	}
	if (_tmp32_) {
		haste_applet_new_haste_view_show_error_message (self, "Error. Connection to server failed.");
	} else {
		const gchar* _tmp37_ = NULL;
		const gchar* _tmp38_ = NULL;
		const gchar* _tmp39_ = NULL;
		gchar* _tmp40_ = NULL;
		HasteAppletHistoryView* _tmp41_ = NULL;
		const gchar* _tmp42_ = NULL;
		GtkEntry* _tmp43_ = NULL;
		const gchar* _tmp44_ = NULL;
		const gchar* _tmp45_ = NULL;
		GtkTextBuffer* _tmp46_ = NULL;
		GtkEntry* _tmp47_ = NULL;
		GtkStack* _tmp48_ = NULL;
		haste_applet_new_haste_view_dismiss_error_message (self);
		_tmp37_ = self->priv->_protocol;
		_tmp38_ = self->priv->_haste_address;
		_tmp39_ = link;
		_tmp40_ = g_strdup_printf ("%s://%s/%s", _tmp37_, _tmp38_, _tmp39_);
		_g_free0 (link);
		link = _tmp40_;
		_tmp41_ = self->history_view;
		_tmp42_ = link;
		_tmp43_ = self->title_entry;
		_tmp44_ = gtk_entry_get_text (_tmp43_);
		_tmp45_ = _tmp44_;
		haste_applet_history_view_add_to_history (_tmp41_, _tmp42_, _tmp45_);
		_tmp46_ = self->priv->textbuffer;
		gtk_text_buffer_set_text (_tmp46_, "", 0);
		_tmp47_ = self->title_entry;
		gtk_entry_set_text (_tmp47_, "");
		_tmp48_ = _data3_->stack;
		gtk_stack_set_visible_child_name (_tmp48_, "history_view");
	}
	_tmp49_ = self->post_button;
	gtk_button_set_label (_tmp49_, "Haste it!");
	_tmp50_ = self->title_entry;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp50_, TRUE);
	_tmp51_ = self->textview;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp51_, TRUE);
	_tmp52_ = self->post_button;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp52_, TRUE);
	_tmp53_ = self->post_button;
	_tmp54_ = gtk_bin_get_child ((GtkBin*) _tmp53_);
	g_object_set (_tmp54_, "margin", 5, NULL);
	_g_free0 (title);
	_g_free0 (link);
}


static void ___lambda23__soup_session_callback (SoupSession* session, SoupMessage* msg, gpointer self) {
	__lambda23_ (self, session, msg);
	block3_data_unref (self);
}


static void haste_applet_new_haste_view_upload_haste (HasteAppletNewHasteView* self, SoupSession* session, GtkStack* stack) {
	Block3Data* _data3_;
	GtkStack* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkEntry* _tmp3_ = NULL;
	GtkTextView* _tmp4_ = NULL;
	GtkButton* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	gchar* url = NULL;
	const gchar* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	SoupMessage* message = NULL;
	SoupMessage* _tmp17_ = NULL;
	SoupMemoryUse buffer = 0;
	GtkTextBuffer* _tmp18_ = NULL;
	GtkTextIter _tmp19_ = {0};
	GtkTextIter _tmp20_ = {0};
	GtkTextIter _tmp21_ = {0};
	GtkTextIter* _tmp22_ = NULL;
	GtkTextIter _tmp23_ = {0};
	GtkTextIter* _tmp24_ = NULL;
	GtkTextBuffer* _tmp25_ = NULL;
	GtkTextIter* _tmp26_ = NULL;
	GtkTextIter* _tmp27_ = NULL;
	GtkTextIter _tmp28_ = {0};
	GtkTextIter _tmp29_ = {0};
	gchar* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	guint8* _tmp32_ = NULL;
	gint _tmp32__length1 = 0;
	guint8* _tmp33_ = NULL;
	gint _tmp33__length1 = 0;
	SoupSession* _tmp34_ = NULL;
	SoupMessage* _tmp35_ = NULL;
	GtkButton* _tmp36_ = NULL;
	GtkWidget* _tmp37_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (session != NULL);
	g_return_if_fail (stack != NULL);
	_data3_ = g_slice_new0 (Block3Data);
	_data3_->_ref_count_ = 1;
	_data3_->self = g_object_ref (self);
	_tmp0_ = stack;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data3_->stack);
	_data3_->stack = _tmp1_;
	haste_applet_new_haste_view_dismiss_error_message (self);
	_tmp2_ = self->post_button;
	gtk_button_set_label (_tmp2_, "Hasting...");
	_tmp3_ = self->title_entry;
	_tmp4_ = self->textview;
	_tmp5_ = self->post_button;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp5_, FALSE);
	gtk_widget_set_sensitive ((GtkWidget*) _tmp4_, FALSE);
	gtk_widget_set_sensitive ((GtkWidget*) _tmp3_, FALSE);
	_tmp6_ = self->priv->_haste_address;
	_tmp7_ = g_str_has_suffix (_tmp6_, "/");
	if (_tmp7_) {
		const gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		_tmp8_ = self->priv->_haste_address;
		_tmp9_ = self->priv->_haste_address;
		_tmp10_ = strlen (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp12_ = string_slice (_tmp8_, (glong) 0, (glong) (_tmp11_ - 1));
		_tmp13_ = _tmp12_;
		haste_applet_new_haste_view_set_haste_address (self, _tmp13_);
		_g_free0 (_tmp13_);
	}
	_tmp14_ = self->priv->_protocol;
	_tmp15_ = self->priv->_haste_address;
	_tmp16_ = g_strdup_printf ("%s://%s/documents", _tmp14_, _tmp15_);
	url = _tmp16_;
	_tmp17_ = soup_message_new ("POST", url);
	message = _tmp17_;
	buffer = SOUP_MEMORY_COPY;
	_tmp18_ = self->priv->textbuffer;
	gtk_text_buffer_get_bounds (_tmp18_, &_tmp19_, &_tmp20_);
	_g_free0 (self->priv->start_iter);
	_tmp21_ = _tmp19_;
	_tmp22_ = __gtk_text_iter_dup0 (&_tmp21_);
	self->priv->start_iter = _tmp22_;
	_g_free0 (self->priv->end_iter);
	_tmp23_ = _tmp20_;
	_tmp24_ = __gtk_text_iter_dup0 (&_tmp23_);
	self->priv->end_iter = _tmp24_;
	_tmp25_ = self->priv->textbuffer;
	_tmp26_ = self->priv->start_iter;
	_tmp27_ = self->priv->end_iter;
	_tmp28_ = *_tmp26_;
	_tmp29_ = *_tmp27_;
	_tmp30_ = gtk_text_buffer_get_text (_tmp25_, &_tmp28_, &_tmp29_, TRUE);
	_g_free0 (self->priv->text);
	self->priv->text = _tmp30_;
	_tmp31_ = self->priv->text;
	_tmp32_ = string_get_data (_tmp31_, &_tmp32__length1);
	_tmp33_ = _tmp32_;
	_tmp33__length1 = _tmp32__length1;
	soup_message_set_request (message, "application/x-www-form-urlencoded", buffer, _tmp33_, (gsize) _tmp33__length1);
	soup_message_set_flags (message, SOUP_MESSAGE_NO_REDIRECT);
	_tmp34_ = session;
	_tmp35_ = _g_object_ref0 (message);
	soup_session_queue_message (_tmp34_, _tmp35_, ___lambda23__soup_session_callback, block3_data_ref (_data3_));
	_tmp36_ = self->post_button;
	_tmp37_ = gtk_bin_get_child ((GtkBin*) _tmp36_);
	g_object_set (_tmp37_, "margin", 5, NULL);
	_g_object_unref0 (message);
	_g_free0 (url);
	block3_data_unref (_data3_);
	_data3_ = NULL;
}


void haste_applet_new_haste_view_show_error_message (HasteAppletNewHasteView* self, const gchar* message) {
	GtkLabel* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkRevealer* _tmp3_ = NULL;
	GtkRevealer* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (message != NULL);
	_tmp0_ = self->priv->error_message_label;
	_tmp1_ = message;
	gtk_label_set_label (_tmp0_, _tmp1_);
	_tmp2_ = self->priv->error_message_label;
	gtk_widget_show ((GtkWidget*) _tmp2_);
	_tmp3_ = self->priv->error_message_revealer;
	gtk_revealer_set_reveal_child (_tmp3_, TRUE);
	_tmp4_ = self->priv->error_message_revealer;
	gtk_widget_show ((GtkWidget*) _tmp4_);
}


void haste_applet_new_haste_view_dismiss_error_message (HasteAppletNewHasteView* self) {
	GtkLabel* _tmp0_ = NULL;
	GtkRevealer* _tmp1_ = NULL;
	GtkRevealer* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->error_message_label;
	gtk_label_set_label (_tmp0_, "");
	_tmp1_ = self->priv->error_message_revealer;
	gtk_widget_hide ((GtkWidget*) _tmp1_);
	_tmp2_ = self->priv->error_message_revealer;
	gtk_revealer_set_reveal_child (_tmp2_, FALSE);
}


const gchar* haste_applet_new_haste_view_get_haste_address (HasteAppletNewHasteView* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_haste_address;
	result = _tmp0_;
	return result;
}


void haste_applet_new_haste_view_set_haste_address (HasteAppletNewHasteView* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_haste_address);
	self->priv->_haste_address = _tmp1_;
	g_object_notify ((GObject *) self, "haste-address");
}


const gchar* haste_applet_new_haste_view_get_protocol (HasteAppletNewHasteView* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_protocol;
	result = _tmp0_;
	return result;
}


void haste_applet_new_haste_view_set_protocol (HasteAppletNewHasteView* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_protocol);
	self->priv->_protocol = _tmp1_;
	g_object_notify ((GObject *) self, "protocol");
}


gboolean haste_applet_new_haste_view_get_is_editing (HasteAppletNewHasteView* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_is_editing;
	result = _tmp0_;
	return result;
}


void haste_applet_new_haste_view_set_is_editing (HasteAppletNewHasteView* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_editing = _tmp0_;
	g_object_notify ((GObject *) self, "is-editing");
}


gboolean haste_applet_new_haste_view_get_haste_address_invalid (HasteAppletNewHasteView* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_haste_address_invalid;
	result = _tmp0_;
	return result;
}


void haste_applet_new_haste_view_set_haste_address_invalid (HasteAppletNewHasteView* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_haste_address_invalid = _tmp0_;
	g_object_notify ((GObject *) self, "haste-address-invalid");
}


static void haste_applet_new_haste_view_class_init (HasteAppletNewHasteViewClass * klass) {
	haste_applet_new_haste_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (HasteAppletNewHasteViewPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_haste_applet_new_haste_view_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_haste_applet_new_haste_view_set_property;
	G_OBJECT_CLASS (klass)->finalize = haste_applet_new_haste_view_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS, g_param_spec_string ("haste-address", "haste-address", "haste-address", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), HASTE_APPLET_NEW_HASTE_VIEW_PROTOCOL, g_param_spec_string ("protocol", "protocol", "protocol", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), HASTE_APPLET_NEW_HASTE_VIEW_IS_EDITING, g_param_spec_boolean ("is-editing", "is-editing", "is-editing", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS_INVALID, g_param_spec_boolean ("haste-address-invalid", "haste-address-invalid", "haste-address-invalid", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void haste_applet_new_haste_view_instance_init (HasteAppletNewHasteView * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self->priv = HASTE_APPLET_NEW_HASTE_VIEW_GET_PRIVATE (self);
	self->priv->start_iter = NULL;
	self->priv->end_iter = NULL;
	self->priv->text = NULL;
	_tmp0_ = g_strdup ("hastebin.com");
	self->priv->_haste_address = _tmp0_;
	_tmp1_ = g_strdup ("http");
	self->priv->_protocol = _tmp1_;
	self->priv->_is_editing = FALSE;
	self->priv->_haste_address_invalid = FALSE;
}


static void haste_applet_new_haste_view_finalize (GObject* obj) {
	HasteAppletNewHasteView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteView);
	_g_object_unref0 (self->priv->textbuffer);
	_g_free0 (self->priv->start_iter);
	_g_free0 (self->priv->end_iter);
	_g_object_unref0 (self->priv->error_message_revealer);
	_g_object_unref0 (self->priv->error_message_label);
	_g_object_unref0 (self->title_entry);
	_g_object_unref0 (self->textview);
	_g_object_unref0 (self->post_button);
	_g_free0 (self->priv->text);
	_g_free0 (self->priv->_haste_address);
	_g_free0 (self->priv->_protocol);
	_g_object_unref0 (self->history_view);
	G_OBJECT_CLASS (haste_applet_new_haste_view_parent_class)->finalize (obj);
}


GType haste_applet_new_haste_view_get_type (void) {
	return haste_applet_new_haste_view_type_id;
}


GType haste_applet_new_haste_view_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (HasteAppletNewHasteViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) haste_applet_new_haste_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HasteAppletNewHasteView), 0, (GInstanceInitFunc) haste_applet_new_haste_view_instance_init, NULL };
	haste_applet_new_haste_view_type_id = g_type_module_register_type (module, gtk_grid_get_type (), "HasteAppletNewHasteView", &g_define_type_info, 0);
	return haste_applet_new_haste_view_type_id;
}


static void _vala_haste_applet_new_haste_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	HasteAppletNewHasteView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteView);
	switch (property_id) {
		case HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS:
		g_value_set_string (value, haste_applet_new_haste_view_get_haste_address (self));
		break;
		case HASTE_APPLET_NEW_HASTE_VIEW_PROTOCOL:
		g_value_set_string (value, haste_applet_new_haste_view_get_protocol (self));
		break;
		case HASTE_APPLET_NEW_HASTE_VIEW_IS_EDITING:
		g_value_set_boolean (value, haste_applet_new_haste_view_get_is_editing (self));
		break;
		case HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS_INVALID:
		g_value_set_boolean (value, haste_applet_new_haste_view_get_haste_address_invalid (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_haste_applet_new_haste_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	HasteAppletNewHasteView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, HASTE_APPLET_TYPE_NEW_HASTE_VIEW, HasteAppletNewHasteView);
	switch (property_id) {
		case HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS:
		haste_applet_new_haste_view_set_haste_address (self, g_value_get_string (value));
		break;
		case HASTE_APPLET_NEW_HASTE_VIEW_PROTOCOL:
		haste_applet_new_haste_view_set_protocol (self, g_value_get_string (value));
		break;
		case HASTE_APPLET_NEW_HASTE_VIEW_IS_EDITING:
		haste_applet_new_haste_view_set_is_editing (self, g_value_get_boolean (value));
		break;
		case HASTE_APPLET_NEW_HASTE_VIEW_HASTE_ADDRESS_INVALID:
		haste_applet_new_haste_view_set_haste_address_invalid (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



